// Автоматично оновлено: 2026-09-06 11:50 UTC
// НЕ редагуй вручну — файл перезаписується GitHub Actions щодня

const CONTENT = {
  "telegram": [
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Очікування на міжбанк на тиждень: 44,50-44,85 грн. Слідкуємо за верхнею межею, поборення якої від...",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628575.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/640",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 31 СЕРПНЯ – 4 ВЕРЕСНЯ 2026. ДОЛЛАР НА ІГЛІ ІНТЕРВЕНЦІЙ НБ...",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628553.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/639",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "МІЖБАНК: За тиждень, середньодобова купівля валюти зросла на 5,6% тиж/тиж до 434,8 млн дол. Це ма...",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628498.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/636",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 31 СЕРПНЯ – 4 ВЕРЕСНЯ 2026. ДОЛЛАР НА ІГЛІ ІНТЕРВЕНЦІЙ НБ...",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628318.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/635",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 31 СЕРПНЯ – 4 ВЕРЕСНЯ 2026. ДОЛЛАР НА ІГЛІ ІНТЕРВЕНЦІЙ НБ...",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628286.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/634",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Тижневий огляд валютного ринку вже на каналі https://youtu.be/SIlOBjFCVeQ",
      "excerpt": "",
      "date": "5 вересня 2026",
      "dateTS": 1788628156.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/633",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Бюджет 2027 готують виходячи з сценарію продовження війни весь 2027 рік.  Для такого сценарію пот...",
      "excerpt": "",
      "date": "4 вересня 2026",
      "dateTS": 1788537119.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/632",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Удар по кабінету голови СБУ Поклада це демонстрація. Й відверто кажучи якісна. А-ля можемо, й нав...",
      "excerpt": "",
      "date": "4 вересня 2026",
      "dateTS": 1788535273.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/631",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "По безготівковим операціям населення двіж - тижнева середня на максимальних рівнях з початку 2024...",
      "excerpt": "",
      "date": "4 вересня 2026",
      "dateTS": 1788526031.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/630",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Як красиво укатали продажами долар.   міжбанк: 44.50 - 44.54  Інтервенції НБУ дуже значні. Попере...",
      "excerpt": "",
      "date": "4 вересня 2026",
      "dateTS": 1788524448.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/629",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦІНИ ПШЕНИЦІ ТА КУКУРУЗИ ПАДАЮТЬ НА СВІТОВИХ РИНКАХ  Ринки суттєво коректуються по зерну, як пише...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788447224.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/628",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "https://news.telegraf.com.ua/ukr/dengi/5949144-rosiyski-teroristi-namagayutsya-zlamati-privatbank...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788446395.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/627",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Сьогодні в етері Новини Live озвучив один з негативних прогнозів долару на 2027 https://novyny.li...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788443612.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/626",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Україна пройшла пікові виплати по обслуговуванню боргу у серпні (а ми й не відчули😊) - виплатила ...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788441833.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/625",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Незважаючи на публічні заяви про жорстку економію та нестачу коштів, Мінфін проводить дуже обереж...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788441385.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/624",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "За результатами серпня 2026 середньодобовий показник вкладень банків в депозитні сертифікати овер...",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788436589.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/623",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Долар розпочинає торги на міжбанку зі зростання 44.72 - 44.78 грн - зараз це 9ти денний максимум.",
      "excerpt": "",
      "date": "3 вересня 2026",
      "dateTS": 1788421816.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/622",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БАЛАНС ВАЛЮТНОГО РИНКУ Офіційно по серпню 2026 від НБУ  МІЖБАНК - попит 8505 млн дол (-3,5%) - пр...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788364890.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/621",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Підверджений факт - валютні інтервенції серпня 2026 - 3й найбільший показник в історії України - ...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788359365.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/620",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПРИБУТКИ БІЗНЕСУ У 2КВ2026 - РЕКОРДНІ ЗДОБУТКИ З ЧІТКОЮ КОНЦЕНТРАЦІЄЮ  Держстат опублікував дані ...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788356833.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/619",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПРИБУТКИ БІЗНЕСУ У 2КВ2026 - РЕКОРДНІ ЗДОБУТКИ З ЧІТКОЮ КОНЦЕНТРАЦІЄЮ  Держстат опублікував дані ...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788355928.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/618",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "рубль на максимумах з березня 2025 ...мало... але це початок, попередній максимум оновлено, а отж...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788354040.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/616",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "❗️Сейчас мы переживаем энергетический кризис. Украина решила, что хочет взрывать российские энерг...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788352264.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/615",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар стрімко відновлюється. Після вчорашніх нижче за 44,50, зараз 44.65  - 44.68  Й коре...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788344222.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/613",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЕURUSD відновив падіння, й сьогодні ходив на 1,156 - мінімум за 10днів  Падіння відбувається незв...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788335016.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/612",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "У серпні 2026 митниця перерахувала в бюджет 75,1 млрд грн. Падіння 3,2 млрд грн до липня, й 3 млр...",
      "excerpt": "",
      "date": "2 вересня 2026",
      "dateTS": 1788334428.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/611",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Глобальний сукупний індекс державних облігацій Bloomberg досяг 3,72% у вересні 2026 року, що стал...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788269750.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/609",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Останні ставки на Polimarket показують, що демократи впевнено займуть й Конгрес й Палату Представ...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788268983.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/608",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "А як же є-бачок, є-ясла, є-зимова підтримка, є-оселя, є-...,  всім по 1000 грн й т.д? ))  А як що...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788259888.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/607",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Вже 2 дні поспіль на міжбанку по долару заходить на територію нижче 44,50грн Сьогодні було 44,46-...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788252796.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/606",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ІТ ЕКСПОРТ - ПОВЗЕМО ПО ДНУ  IT експорт - 567 млн дол в липні (+1%м/м, +2,1%р/р), та 3,91 млрд до...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788251056.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/605",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВИТРАТИ УКРАЇНЦІВ ЗА КОРДОНОМ В ЛИПНІ 2026 ДОСЯГЛИ 759млн дол - МАКСИМУМ З ПОЧАТКУ РОКУ  В порівн...",
      "excerpt": "",
      "date": "1 вересня 2026",
      "dateTS": 1788250398.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/604",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ГОЛОВНЕ. У ЛИПНІ 2026 ЕКСПОРТ УКРАЇНИ ВПАВ НА 11,1% ДО ПОПЕРЕДНЬОГО МІСЯЦЯ  Це дані НБУ, й рахуно...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788193964.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/603",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПЛАТІЖНИЙ БАЛАНС ЧЕРГОВИЙ ДЕФІЦИТ  Платіжний баланс України в липні зведений з дефіцитом 682млн д...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788193186.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/602",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПРИВАТНІ ГРОШОВІ ПЕРЕКАЗИ ЗА 7М2026 ВПАЛИ НА 6,3%  В липні 2026 приватні перекази зросли на 3,4% ...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788192350.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/601",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНІ БЕЗГОТІВКОВІ ОПЕРАЦІЇ НАСЕЛЕННЯ  Після лібералізації валютних операцій для безготівкових ...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788191481.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/600",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ШІ ПОРТФЕЛЬ (результат липня, портфель на серпень)  Як й обіцяв в (https://t.me/shevchyshyn_trend...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788190615.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/599",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БРУТТО ЗАРПЛАТИ В ЛИПНІ ₴32 243  Це значно менше моїх очікувань (₴32,9К). Я закладав ріст на друг...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788182296.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/598",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Спочатку розісратись з партнерами, а потім запросити дружити проти Китаю 🤡  Харизма - 100, рівень...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788178480.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/597",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Экспорт агропродукции из Украины в августе рухнул почти наполовину, — Forbes  Украина за 1–27 авг...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788172767.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/596",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Тут Axios.com пише що в Америці проблеми з цінами.  Дизель, кукуруза та пшениця формують значний ...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788164504.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/595",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Запаси нафти в США на мінімумах майже на 50річних мінімумах. Й угода з Венесуелою, як й її контро...",
      "excerpt": "",
      "date": "31 серпня 2026",
      "dateTS": 1788163308.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/593",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Після паузи відновив публікацію відео на каналі по валютному ринку.  Тому традиційно, якщо ліньки...",
      "excerpt": "",
      "date": "30 серпня 2026",
      "dateTS": 1788106937.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/592",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ СЕРПНЯ: БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: ...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788021219.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/591",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ СЕРПНЯ: БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: ...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788021192.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/590",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ СЕРПНЯ: БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: ...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788021144.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/589",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Попит на валюту стабільний, а пропозиція валюти падає потижнево з початку серпня. Дефіцит стрімко...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788021076.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/587",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ СЕРПНЯ: БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: ...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788020770.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/585",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ СЕРПНЯ: БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: ...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788020665.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/584",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ви зараз в мене тапками почнете кидати, але на душі так херово, що не вистачає такого собі \"Арест...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1788002064.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/583",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Національний банк з 1 вересня 2026 року планує розраховувати довідкове значення курсу гривні до є...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1787996318.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/582",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Після удару 5 серпня, коли жодна балістика не була збита, я написав про дробину ескалації Серед і...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1787994021.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/581",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ  За літо 2026 НБУ продав на міжбанку 14,7 млрд дол (моя оцінка).   Ці більше ніж НБУ за...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1787989493.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/580",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНІ ІНТЕРАЕНЦІЇ НБУ - ПРОДОВЖЕННЯ РЕКОРДНОЇ СЕРІЇ  7 тижнів поспіль НБУ заливає ринок валютни...",
      "excerpt": "",
      "date": "29 серпня 2026",
      "dateTS": 1787989345.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/579",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ДЕ МЕЖА ЛОГІСТИКИ ТА РИТЕЙЛУ ДЛЯ КИЇВСЬКОГО РЕГІОНУ  Знищення складів випереджає їх відбудову у 1...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787931278.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/578",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "EURUSD вниз рвануло, бо глава ФРС заявив що потрібно боротись з інфляцією, й ринок повернувся до ...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787928912.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/577",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "МВФ в Києві, закон про оподаткування посилок від 150 євро очікує на голосування в Раді.  Від ріше...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787912548.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/576",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Рубль рф в лідерах світового падіння до долару з початку серпня 2026р (станом на 28.08.26) ...мал...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787910253.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/575",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "EURUSD конценсус прогнози від Bloomberg 1. В середньому та медіально всі ціляться на зростання єв...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787910002.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/574",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "В догонку до останнього абзацу попереднього посту: - За даними профільних аналітиків та RAU, у Ки...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787907127.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/573",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "СКІЛЬКИ ВТРАЧАЄ МІСТО КИЇВ ЧЕРЕЗ ПРОСТОЙ У ПОСТІЙНУ ТРИВОГУ  Коротка відповідь: якщо не враховува...",
      "excerpt": "",
      "date": "28 серпня 2026",
      "dateTS": 1787906800.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/572",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "❌💰Супермаркети можуть залишити виробників без оплати за знищені Росією товари.  За чинними догово...",
      "excerpt": "",
      "date": "27 серпня 2026",
      "dateTS": 1787850147.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/571",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "НБУ збільшив агроекспортерам строк повернення валютної виручки зі 120 до 150 днів.  Це поки вигля...",
      "excerpt": "",
      "date": "27 серпня 2026",
      "dateTS": 1787811168.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/570",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "УКРАЇНСЬКІ БАНКИ ЗА 7М2026 СКОРОТИЛИ ЧИСТИЙ ПРИБУТОК ДО 62,5 МЛРД ГРН.   В порівнянні з 7м2025 ро...",
      "excerpt": "",
      "date": "26 серпня 2026",
      "dateTS": 1787765463.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/569",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "РОЗДРІБНІ ПРОДАЖІ В УКРАЇНІ СТАБІЛЬНІСТЬ. ЗА 7М2026 +9%  Здається все стабільно. Роздрібні продаж...",
      "excerpt": "",
      "date": "26 серпня 2026",
      "dateTS": 1787759839.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/568",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БЛОКУВАННЯ ЧОРНОГО МОРЯ ЖЕНЕ ЦІНИ КУКУРУЗИ ТА ПШЕНИЦІ ВГОРУ  Чиказька пшениця подорожчала до макс...",
      "excerpt": "",
      "date": "26 серпня 2026",
      "dateTS": 1787741453.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/567",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Європейські країни дедалі частіше зазнають кібератак, підпалів, диверсій та польотів озброєних бе...",
      "excerpt": "",
      "date": "26 серпня 2026",
      "dateTS": 1787740796.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/566",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "КІЛЬКІСТЬ ВКЛАДНИКІВ БАНКІВ, СТАНОМ НА 1 ЛИПНЯ 2026  Згідно даних НБУ та ФГВФО, на 1 липня було 7...",
      "excerpt": "",
      "date": "25 серпня 2026",
      "dateTS": 1787675262.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/563",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Як вели себе різні категорії власників в 2026 році, згідно з даними ФГВФО й останнього звіту  👉На...",
      "excerpt": "",
      "date": "25 серпня 2026",
      "dateTS": 1787670779.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/562",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Фонд гарантування вкладів фіз осіб перестав публікувати статистику по кількості вкладників по сум...",
      "excerpt": "",
      "date": "25 серпня 2026",
      "dateTS": 1787669228.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/561",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БАНКИ ЗАВОЗЯТЬ ФІЗИЧНЕ ЗОЛОТО ЩОБ ЩО?  Станом на 1 липня українські банки мали банківських металі...",
      "excerpt": "",
      "date": "25 серпня 2026",
      "dateTS": 1787667075.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/560",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "За 7м2026 банки завезли готівкової валюти на 18% меньше ніж рік тому - 5,48 млрд дол.  В структур...",
      "excerpt": "",
      "date": "25 серпня 2026",
      "dateTS": 1787663625.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/559",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "П🤬дець... особливо в умовах блокади портів та недостатності місць для зберігання. Критичності сит...",
      "excerpt": "",
      "date": "21 серпня 2026",
      "dateTS": 1787293550.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/558",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "КРЕДИТУВАННЯ БАНКАМИ ЗА 6М2026  Лідери зростання кредитного портфелю серед банків за 6міс2026): 📈...",
      "excerpt": "",
      "date": "16 серпня 2026",
      "dateTS": 1786864459.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/557",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БАНКИ ЛІДЕРИ ЗРОСТАННЯ СТРОКОВИХ ДЕПОЗИТІВ НАСЕЛЕННЯ ЗА 6МІС2026: 📈Строкові депозити гривні: 1️⃣ ...",
      "excerpt": "",
      "date": "16 серпня 2026",
      "dateTS": 1786864264.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/556",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "💰Рейтинг прибутковості банків за 6міс2026: 1️⃣ПриватБанк: 24,56 млрд грн (проти 34,88 млрд грн то...",
      "excerpt": "",
      "date": "16 серпня 2026",
      "dateTS": 1786862217.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/555",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Чистий прибуток банків України за 6м2026 впав на 30,7% до 54,07 млрд грн. Це мінімум з 2022 року....",
      "excerpt": "",
      "date": "15 серпня 2026",
      "dateTS": 1786794753.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/554",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Згідно даних НБУ, доля строкових депозитів населення у липні зросла з 32,6% до 32,8%.  Всього нас...",
      "excerpt": "",
      "date": "15 серпня 2026",
      "dateTS": 1786792848.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/553",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Банки кредитують органи держвлади рекордними темпами з січня 2021 року.  Приріст кредитів станови...",
      "excerpt": "",
      "date": "15 серпня 2026",
      "dateTS": 1786792510.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/552",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "З 16 липня міжбанк майже не виходить з зони екстремального навантаження на резерви, де середньодо...",
      "excerpt": "",
      "date": "15 серпня 2026",
      "dateTS": 1786791442.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/551",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ГОТІВКОВИЙ ВАЛЮТНИЙ РИНОК Помірне відновлення чистого попиту, з новими статистичними викидами, як...",
      "excerpt": "",
      "date": "15 серпня 2026",
      "dateTS": 1786790473.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/550",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "За 12 днів серпня, падіння експорту пшениці та ячменю майже на 80%, кукурудзи майже на 60%.  Це н...",
      "excerpt": "",
      "date": "12 серпня 2026",
      "dateTS": 1786540834.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/546",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "💰\"Збитки колосальні\": у Rozetka назвали вартість зруйнованого Росією складу.  Зруйнований російсь...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786466547.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/545",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Тут без коментарів. Суд та ДБР мають надати свої висновки.  Але здається, що без ніякого попередн...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786450102.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/544",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ДБР открыло дело о подделке диплома Пышного  Шевченковский райсуд Киева обязал ДБР внести сведени...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786448227.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/542",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "А знаєте чому таке послаблення? Й не буде впливу на готівковий ринок (не очікується).  Тому що за...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786389322.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/541",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "❗️НБУ в четыре раза увеличивает лимит на покупку валюты для украинцев - до 200 тысяч грн в месяц ...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786389103.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/540",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар 44.89 - 44.91  Зупинка на максимумах, завтра продовжуємо зростання. #міжбанк #usduah",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786373933.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/539",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Липень ще норм пройшов. Я рахував +0,7%. Вийшло краще. Серпень-вересень буде жорсткіше. Значно. Б...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786373865.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/538",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Не почую - не повірю Але дуже сподіваюсь --- ❗️США ежемесячно будут выделять Украине ракеты-перех...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786186281.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/537",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ З початку літа 2026 НБУ залив у ринок $10,9 млрд валютних інтервенцій.   Всього за 2 мі...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786181529.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/536",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЩОДО РЕЗУЛЬТАТІВ 1ГО ТЕНДЕРУ 3х МІСЯЧНИХ ДЕПСЕРТИФІКАТІВ  Якщо коротко: ставка розміщення 3МДС ст...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786178285.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/535",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Якщо темпи виїзду першого піврічча в 2025 році будуть збережені, то по року можемо отримати найбі...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786176574.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/534",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "як не згадати класику...  )))",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786110899.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/533",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Загадкові надходження до ЗВР, особливо по новій програмі USL.  Гроші заходять по USL? - так.  У З...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786110610.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/532",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Міжнародні резерви України 51,2 млрд дол НБУ",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786105879.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/531",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЧИСТИЙ ПОПИТ НАСЕЛЕННЯ НА ГОТІВКОВИЙ ЄВРО ВИПЕРЕДЖАЄ ПОПИТ НА ДОЛАР  За липень 2026 чиста купівля...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786105710.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/530",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Доречі, сьогодні, 7 серпня, перший тендер за тримісячними ДС.  Замість повного задоволення заявок...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786101402.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/529",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Цікаво 🤪  Зазвичай мене просять долучитись до рейтингування, а тут сам попав в рейтинг )",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786098383.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/528",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "До попереднього посту #НБУ #інфляція #ВВП",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786098007.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/527",
      "external": true,
      "featured": false
    }
  ],
  "news": [
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "From-UA",
      "title": "Чи потрібна Україні банкнота номіналом 5000 грн — оцінка інфляції та купівельної спроможності від аналітика - From-UA",
      "excerpt": "Згадка у виданні From-UA",
      "date": "4 вересня 2026",
      "dateTS": 1788537000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPYkF1RGFBQVdNTmtaUmRGRFZiRWtncGhRZ3pmV1pyWnRTSTN4QTVHREF3OVo5TnJHUmJ6SGtOWlZGamduQzlkZjE1Ml9XQmtaZ3k0ZUZILXJZdnJEMkxndFRkdjlBZ1ZDM0dCTW5YMjkyTE54bzlGeUNNdDVfbWotNGk3eExnaDF0ZFFfVW9XRkNNSEpMRkVFUnJiM2U4YUNtUWNySW1hUVVCVWUxSUZiVXIzdk9iUjMwbnhqUXZlTVJvaUxFeUR1dURsRG44QdIB0wFBVV95cUxQTWlpSWVVNDFEZE12QUhWNW94S2tFVndVRE9uOEgyTUpnaWwxRFBRWFloQkU5T3ZOa1hveFJNdXVWV01NRHJ5OV85U1dsVFh2NDJWYXF2bVVYeWFsaEl0V2Vwei1IbThUVTUwMFJoZENPT2xuZFVhUjdLT20zNFJOYmY1ZUxqMldCdTVYaDQzd3FEQTU5eVNVVU9TejVxWjdZb1BNUWRWY1ZISUdsS1NiWGFIR0lIV1dPZGlsenlsQ3NLUGVEbjZEOGJYcEFZeE9VWGQ4?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "РБК-Україна",
      "title": "Банкнота 2000 грн може стати новою нормою для закупівель: аналітик пояснив, що буде з цінами - РБК-Україна",
      "excerpt": "Згадка у виданні РБК-Україна",
      "date": "4 вересня 2026",
      "dateTS": 1788524100.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxOcXp5X0tscTFuRDZCNjNJQ3VDaU91QktlYWctOURQOV9EZGJ2WDYwcmVrTTA1VS1iNjExSXVkcHp0UERsSTlmV0g4WV9QRVdDXzhuWS1KdEJGNGczZUd4MGJuMmhkZ3ZsQlE5NWtpTldXT3BlSzNIYTZsU0RsSFV2ck9GQzZmWmYtT0VmN0xZTmJqZ9IBlwFBVV95cUxPOG9ieXA3MUhUdWpUMXJycHh5VjU4UU9nTUt4VUQ0YWRKQTdKN2pDN3VQZTZnSDc3ckxHa3R3N0NUTWZ6RktYQTZSQi1DN2oxb2ZyX0JnM2d6bUFXUDNNc1pKdjRvTHdQajlPWmhiZFhqdnJxWVVfN1plbEtmYUFRQmlzZW4tQWlnaVFGMjF1c2Z5Wm42SUo0?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "1plus1.ua",
      "title": "Що чекає на курс валют у вересні: економіст назвав три сценарії для гривні восени 2026 року - 1plus1.ua",
      "excerpt": "Згадка у виданні 1plus1.ua",
      "date": "1 вересня 2026",
      "dateTS": 1788274143.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxQLVJTbjlEVks5ZGR2dTdCLW8tU0FwekxUM0d6Wlo2dXdKWWNDQWdpTnQ3czF1dzdqMTREbzhlM285dWYtS2FoRUliN0F5ZWVINzIzQ1JzS2NuNmlmWUhMN2RCdW9YYWxZSFlqODg5NlVNMi1qcDJQM1hqZEZ0ekxKV0tCbkdSN1hpWG5LNVMwZVBYMldBdjRTZFM3eG83SUhyYlk5a2pvT2xLLW5lOENENWYteWJZblhudHVRR2VUVjgzTHNiMmfSAcYBQVVfeXFMUC1SU245RFZLOWRkdnU3Qi1vLVNBcHpMVDNHelpaNnV3SlljQ0FnaU50N3MxdXc3ajE0RG84ZTNvOXVmLUthaEVJYjdBeWVlSDcyM0NSc0tjbjZpZllITDdkQnVvWGFsWUhZajg4OTZVTTItanAyUDNYamRGdHpMSldLQm5HUjdYaVhuSzVTMGVQWDJXQXY0U2RTN3hvN0lIcmJZOWtqb09sSy1uZThDRDVmLXliWW5YbnR1UUdlVFY4M0xzYjJn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Є три сценарії: економіст ошелешив, що буде із курсом валют в Україні у вересні 2026 - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "1 вересня 2026",
      "dateTS": 1788238800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxONjREZE1RR2pDXzREX2lfcURRUWhWVFJZLWNpZHJuXzBuWXlUY1ZpVTR3VDlVTkgtYXFndFd1LW1IM1Z6VVJyVm05N2ZmQTZQa05QbEdCTzhtRzVvSHphTUxySTlEZTB3aFQ0MlRpaUxPQjFXTmhQRGFlcllIbWQ3SXpCSVI0UTVYRHJwRFk3TVh6WTFvMmZ5VFVWZW1rdnVFMldxTTZnY21sRGtNUG1xRGZ3UWJrU0V2R1RDNXVsTER1Z1ktQlVmeWlB0gHPAUFVX3lxTE1xNU9rNG5mZkt3Vk1TeWRhRDVIYTkxazB4MHBKdmtDRnFnSGpTMF9kN3ZJQWszZzlobl9Nc1d4ZzA3eHZjMVB4aXJLUzZqYk56V1JhSExYSVJ5MUVablhnUmN0Wnp3OTdETk0xbnd2eVlxZDY2cUp5RkRYWDhXMERUeTFiWUZwRGY4QXBEWFd1d21kamRFbnZKSmlPZFBVMHF4X1ZoQ3ZoOEpUUDlKVURVN0FqWkdkQl9NMGtCREMtRFlBZ2VldV9aandqSzJTUQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Курс долара у вересні: експерт розповів, чи очікувати рекордного подорожчання - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "31 серпня 2026",
      "dateTS": 1788172963.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxOWHpRa09Pb1ZOTWEzeXZ4M0xyTENsMjhZa3BRcE5SWkJWRkVDWkdIRG9za3g5RUZEd1lHUjBRUjFwd01zQUVyOVJLQ3JHNzlmcFgzT0FFWGRoRDUyaGEtalRWbmRPdHVHb200QWdxTkZBSFlOTzdyM0N0SjhqSFZ2X0N6OTNuY2FtWDlVVmJ1a215V0QweVRJb1RVQXJaWlhnTWVFeE5DN2FkV2kzT0d2UUxTVHZ4YmhhdWfSAb8BQVVfeXFMTWNnWU5vZm1YdDFScDN2RmdsSXhiRkdwTF9Hcm5KRVUtcUFLNXFrOVFTdmF1X2pVekdaSkdSV2JWQkY5eDVMOEZ5VlpSWC1KcDYzR2g0RkE1ZVFoSHBxS0ZhYWdUWDRTc3lFX3FlNkc2M1ZTLVFocDYwLThtS0FmVExncG5SWDBzT3ZENm5XcThkMzBVbTlaMm54c3ZTbUlDNXNndkJ6Rk45bkljOHlvOGxIQ3o5emNOVF9yNVFOTXM?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Мільйони доларів щодня: скільки коштує Києву одна доба суцільних повітряних тривог - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "28 серпня 2026",
      "dateTS": 1787911567.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxQVk1ZT2FZZ2ZqZEs5bDhSUDZDOUZZU3hvMzNUX3pwbWE3N0lrdU11MmkwTWdnYk5UcEJRRDFRQ296ZVpRUVA2VDBKYzJHVm9wS2thTjRmVjh3WVg1YlNnWmxjQVlmVEFxREF2SjlTTGpaazhMY09lUWtvZzcwaU5PU1pxWTlNWjBHa3ZzZDA0TmZXcjZzMm9ycHJNNzhTMmZoRnBZYkItd2tvOGt4bmVlWXVVTF85eUMzQlo2U3dSWUhZLVE4bGfSAcsBQVVfeXFMTkhZbjZCcFhrdUU5TXExWFVMT1VHVndZaDgyOXFvU1FhaHdGb2RuQ3c3ZGdYNVRFYzJJeXZPME9yYjJiYmt3VTRPYWx3Vmh3QVhtdGo0V3d6ODFFd1RfNUdZeDR3NFdTOUZlaUkxcTA2dDI0bGlhR2xfYUozZ1RnNERIUHdjWnlTeWR2ZFVMTXVQX0xwYl9kYjFXeWowWTVaUFIyejFWMTdia09weW5qNUZnSXdFM0dwZDdYMUJxd0xDODdfYm0wTXI0VVE?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "24 Канал",
      "title": "Мільйони доларів щодня: скільки коштує Києву одна доба суцільних повітряних тривог - 24 Канал",
      "excerpt": "Згадка у виданні 24 Канал",
      "date": "28 серпня 2026",
      "dateTS": 1787911440.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxOSVd4T1VMbGlsUXFFaTJwZk9VcnRmQzU0RGlyTTNqU2hIU1I1RUJROEIxd2tOcTFmUnFna2hWTFN3VXEwRkJzb3ByNkZUODQ3Umo2dnV6TjlzWDlpMEhzZVZhNEdPbkNDYl9KcGFLczRrY3UtakpQZllCNFJTb0tEQzdyY1h0MUNIeU9mNGVUWnVnQdIBlwFBVV95cUxQbWVIVHNkcGJHanRYeXRiLVpvNVh1eUpxSVhNTzNsUDRQY2xiMWNSWnB1bFI1c1E3eFd0eGFxUzNMeXpOblFJUG5PZk1QR1lVSkZmbnNiOXJKR0NIUWVyd21BLTFLMUUtdTI2cnJuZ05oUE1BSUh4Y0ZTeFdwaDV5bHZyR0hJa3pjaTlrclVEV0xZNFBTa1Aw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар може різко злетіти вгору: експерт назвав терміни та новий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "17 серпня 2026",
      "dateTS": 1786999259.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOYWRBOWtqd2s5SkM3d2w1aWd3ZlJTUkdSblRjZEZCekFtdVNoRC1YeVduaVdQWTNFUk5uT2ZqLVFPb0NDbUxPY0h5OU14ZzhFZDFPNHlxa3VVUE40b29ER1FjSi1qNXhHVnFDSndHMHhsTjBCc1FUSktranh4V2ZGXzI2VDhvS3U1MnpYNElNZDNpRzFwR0Y1YXdQdUwwNXBpMGZlSnVsTEF0OXJNaUdQejRicTFBUdIBtgFBVV95cUxOYWRBOWtqd2s5SkM3d2w1aWd3ZlJTUkdSblRjZEZCekFtdVNoRC1YeVduaVdQWTNFUk5uT2ZqLVFPb0NDbUxPY0h5OU14ZzhFZDFPNHlxa3VVUE40b29ER1FjSi1qNXhHVnFDSndHMHhsTjBCc1FUSktranh4V2ZGXzI2VDhvS3U1MnpYNElNZDNpRzFwR0Y1YXdQdUwwNXBpMGZlSnVsTEF0OXJNaUdQejRicTFBUQ?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Гривня може стрімко знецінитися: експерти ошелешили прогнозом про курс валют в Україні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "17 серпня 2026",
      "dateTS": 1786985786.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxOTjVLeEJDZ1NUSkJBcl8tQTdIc0pBNlJIa1VYVWJSWFc1cW9oT29PMzFXQjVrQl9BNkltbGxNWGFnRTNySnlqQzAzcWlxcHE2LVl2a3A2Y0MtS2g5MTNCN09ON2tZdk9KMWY1QVp5TnJYb3JyRUtkTVpNaERsVFIwUjNrSWRuekR5eGNHcmljcVNUZ3U5bU9QemFRM1oyMDFYTmZLNHU3UVA0aTZpV1JuU0wtaEhXNlpoUGNNZzdTWEpNZFJJLTlr0gHMAUFVX3lxTE1WOUd3UGxOVFFxcDhHSXNkdTlQYWxDMWM4SUZ3NzA4NkJUVjkzbkJ5WjJ5Vi1QVThoWktSR1lQT3NTUnhHcE9pVVQ3RXFpbEwyd2tlRUt3WnM1SGd6MUEySk5DVXViQXJfZ2h3QUJXRThBYzI1YTVQTHV5TzJrR3lTeVFVclFjcDNtWERtVmo4Q0Ywa1RqdFZYTTRFcDhpaTRYcU9sZ0hPOTZuYnM0SXhBVWc3aVlqbkxXcW9vamRTeU9iNENOd3oxQ0ZJVg?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Гривня може стрімко знецінитись: експерти ошелешили прогнозом про курс валют в Україні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "17 серпня 2026",
      "dateTS": 1786985786.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNVjlHd1BsTlRRcXA4R0lzZHU5UGFsQzFjOElGdzcwODZCVFY5M25CeVoyeVYtUFU4aFpLUkdZUE9zU1J4R3BPaVVUN0VxaWxMMndrZUVLd1pzNUhnejFBMkpOQ1V1YkFyX2dod0FCV0U4QWMyNWE1UEx1eU8ya0d5U3lRVXJRY3AzbVhEbVZqOENGMGtUanRWWE00RXA4aWk0WHFPbGdITzk2bmJzNEl4QVVnN2lZam5MV3Fvb2pkU3lPYjRDTnd6MUNGSVbSAcwBQVVfeXFMTVY5R3dQbE5UUXFwOEdJc2R1OVBhbEMxYzhJRnc3MDg2QlRWOTNuQnlaMnlWLVBVOGhaS1JHWVBPc1NSeEdwT2lVVDdFcWlsTDJ3a2VFS3daczVIZ3oxQTJKTkNVdWJBcl9naHdBQldFOEFjMjVhNVBMdXlPMmtHeVN5UVVyUWNwM21YRG1WajhDRjBrVGp0VlhNNEVwOGlpNFhxT2xnSE85Nm5iczRJeEFVZzdpWWpuTFdxb29qZFN5T2I0Q053ejFDRklW?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар може різко злетіти вгору: експерт назвав терміни та новий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "17 серпня 2026",
      "dateTS": 1786950000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQTF9qSzJ1Z094UWFRSXE3VmZCYjNXZkJteGNhSlhIbVRJRFZSdXBXcFk3TXlIU3ZfSUJ5T2R6WThfNjFEQmFTYVQ3bWdIQThxajdTWGhncDJ0ZlFwQTdVNnRmUy1HbW1qbnRUcGJsMm1pQUl2bFRkQnBwaERsT0dFRHl1RUdwU3d1VXgxdlBuUy04U0ZrTFZ5SDZ6ZnYyVjdwcV9kUHBVVmE2QlQ0Vno3SdIBtgFBVV95cUxOYWRBOWtqd2s5SkM3d2w1aWd3ZlJTUkdSblRjZEZCekFtdVNoRC1YeVduaVdQWTNFUk5uT2ZqLVFPb0NDbUxPY0h5OU14ZzhFZDFPNHlxa3VVUE40b29ER1FjSi1qNXhHVnFDSndHMHhsTjBCc1FUSktranh4V2ZGXzI2VDhvS3U1MnpYNElNZDNpRzFwR0Y1YXdQdUwwNXBpMGZlSnVsTEF0OXJNaUdQejRicTFBUQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "РБК-Україна",
      "title": "Курс долара 2020: які зміни чекають українців на наступному тижні - РБК-Україна",
      "excerpt": "Згадка у виданні РБК-Україна",
      "date": "8 серпня 2026",
      "dateTS": 1786173845.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQeGpvaDB4Z2dncDh6RzhLNE85cmthOGNkQWp2LVE1M3NXS3RIZ1BMczgzQlc2cjVCdlRzX1lGczE1ak1GOGN2NGFCVFBBSk5PcnVqSGd1NEwyQUxCRFUybXJncWhjc2N1UTBfWjZXcjBSRXVyVmN6OTh5RFhzZlg0YTh4XzRjeWRVT0ZTdGRSNTBEQl9FSmYtS2NnSHHSAZwBQVVfeXFMUHhqb2gweGdnZ3A4ekc4SzRPOXJrYThjZEFqdi1RNTNzV0t0SGdQTHM4M0JXNnI1QnZUc19ZRnMxNWpNRjhjdjRhQlRQQUpOT3J1akhndTRMMkFMQkRVMm1yZ3FoY3NjdVEwX1o2V3IwUkV1clZjejk4eURYc2ZYNGE4eF80Y3lkVU9GU3RkUjUwREJfRUpmLUtjZ0hx?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Радіо ТРЕК",
      "title": "Долар може різко подорожчати вже у серпні: фінансовий аналітик назвав можливий курс - Радіо ТРЕК",
      "excerpt": "Згадка у виданні Радіо ТРЕК",
      "date": "3 серпня 2026",
      "dateTS": 1785763200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxObUduTll4TlFjQjlWQ3Zvdk1vLXhTV3RMbThFNWlTRVoyWm51eEZyaU5BS1NRLWFOY3VlYTAydmhmYnFOYXZKWFdNWHphZzdwaV9UM0EzMDl0c3diMFlWQmFQbGtuOWRsdU1tR0FtQmEtQk43UE5EM1AxWHVFV0hEdlJwME1ZTVBNdTNpckY1VXNjQ0FMTXRWX0N5R1M1dWdOVGY2bDNGMS1hZFMtSHlYRE8zM3VVWDlPakdEZU9kUWIzRmpfSjcw0gHGAUFVX3lxTE84dlZnRHFfYzBSRVZoR3BaWllxSVhsTGF0eEdSXzdYdjk4RGVscGZnSHBfWVl3OHQzOTI0MGFpTkhsb1E4WHN5eDZQZU5FOFBVMlZtNEt0TVY5TjJ2ZHBWSWRqUGdBZ1V0X2FaMFBBUm1wZVo5U2pSXy11ekxRb2ZSQThHcndqZ0tsbnZramw3bmFTdk5RMmF6dXRSTl9ZQUZTOW4xbzRxUXFFU0w2eGdvMVgtQ0V5bXNlZDBYdmMxWXdqVjlkdw?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "УНІАН",
      "title": "До 46 гривень за долар: аналітик пояснив, чому гривня ризикує ослабнути вже у серпні - УНІАН",
      "excerpt": "Згадка у виданні УНІАН",
      "date": "3 серпня 2026",
      "dateTS": 1785749400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxOME5qelBEdFVlWU1CU3RJV2hpXzZHOGtaaE1FMzlPMzBaczlQaGxSeVMxWEVyRWV6MEliWDNFclQtblMtVy1KRGhrejBxanFqNjBkc2xjWkI5dDIzQmxsYUF4UkpkekN4c2NkSkV6VEZWblFBUWpnWWV1OHYtcGxUYXYzbFZVeDRfZi1tR1NJWVd0M3dabU93U1RJTlV0RXlGaFdiUnIyVnVYQVZ3SWFLSG5BT0w3ZW9iOXBJMkZ4R1QzYVFOTk1qQU9GWHpZYnJjYTc5YWIxZEMxWWltanBzd0RvUHFKQlVrb091WUEwb1FFYlphRWZSeGN30gH6AUFVX3lxTE4wTmp6UER0VWVZTUJTdElXaGlfNkc4a1poTUUzOU8zMFpzOVBobFJ5UzFYRXJFZXowSWJYM0VyVC1uUy1XLUpEaGt6MHFqcWo2MGRzbGNaQjl0MjNCbGxhQXhSSmR6Q3hzY2RKRXpURlZuUUFRamdZZXU4di1wbFRhdjNsVlV4NF9mLW1HU0lZV3Qzd1ptT3dTVElOVXRFeUZoV2JScjJWdVhBVndJYUtIbkFPTDdlb2I5cEkyRnhHVDNhUU5OTWpBT0ZYellicmNhNzlhYjFkQzFZaW1qcHN3RG9QcUpCVWtvT3VZQTBvUUViWmFFZlJ4Y3c?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Vesti Ua",
      "title": "Курс долара у серпні: економісти пояснили, до чого готуватися - Vesti Ua",
      "excerpt": "Згадка у виданні Vesti Ua",
      "date": "3 серпня 2026",
      "dateTS": 1785741000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPTTU0OHBTUEtQRWxGWThsTUlZejVCZnp4aHBmUFlaeW5qQWpaRE91YlliOGRVQlc2S2xEU0I2dVh1akdzcjVyNW84aVc2eUNqR1NsWXdQYnR1YUsySkI0SmVGaXJZTFlJZk45SG1UTTN3RG5yRFdweVRRa09GTDZHd3E1QnB3czVCQkM5ODRqS1Jxd08td2xLTlp5SEd0VVpNRzNYdVJlUjY3ckxFU0tydA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Врожай під загрозою: в Україні різко підскочать ціни на один базовий овоч - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "3 серпня 2026",
      "dateTS": 1785740400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNcEg5T3kyTU1kcGdmNWVOcU5aZ3lmS3hwRHBtODQ3QXRVTkEwRnhxNHMydWpKaHEzN0ZtbXVlamY4SnQwdlI4Z21lLXEyOHlRNG5oMDJnTW52VjR0SU83d040MnNjWkZxeU43R2ZJY0d1cE5CV3o5UlVJZ1hsUkhzN19wU01wMlVEVjJSRG12bElxUVpfR1lmVHZSU0lRclQyN0dqTnFOYi11WjdqM1pPdG45OXREQWtw0gG-AUFVX3lxTFAwY3RsQTZjVkNLdm9ReVZ2a2tIcjZnb1h6eU8ySG8xUzQ0bDZJUW1SblZGdG9rTlMya0lhLVREMGdQblBJeGpyUmZMR245ZkRBMVJIVHMzS3ZHOWRCaVN0QlBueXBoLXhhSFU0alVFd1owRjFIRUZ6Y2NGc0dPZEtYMTdOdUZxM2ExYno4cVAxS2J5dVpBLWVnRlR3TE1uaWwyTW9VWHlSZmZPQ3gwQnRjWmhUbnBMOFpjd1BuQUE?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар готується до нового стрибка: експерт назвав терміни та можливий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "2 серпня 2026",
      "dateTS": 1785694880.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxOOE5Mb1M1c0M3UFU3OEt6cG9wUERCaUhuNkRkZk1haW1YRWFHVTkwdUZjM3lpZzVpYzdfOVBJTFRqbTB2b2ZuUHQxWkF1Z1RUM0hyNmpxdjVJNWU3d29QaGRfczl0SGwtZVdEcVdRSGxDRkxFUEZMc1FUbC1fZDlobHpQWi1HREV1YzRHZTJldnV5SGZsWTZCRGRYTHBqY3d1M08wSGZoTkV6Sko4LWZINHFGM3NWX09HLUlQVmdR0gG-AUFVX3lxTE44TkxvUzVzQzdQVTc4S3pwb3BQREJpSG42RGRmTWFpbVhFYUdVOTB1RmMzeWlnNWljN185UElMVGptMHZvZm5QdDFaQXVnVFQzSHI2anF2NUk1ZTd3b1BoZF9zOXRIbC1lV0RxV1FIbENGTEVQRkxzUVRsLV9kOWhselBaLUdERXVjNEdlMmV2dXlIZmxZNkJEZFhMcGpjd3UzTzBIZmhORXpKSjgtZkg0cUYzc1ZfT0ctSVBWZ1E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Економіст попередив про новий стрибок долара: за яких умов курс перевищить 46 гривень - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "2 серпня 2026",
      "dateTS": 1785675600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxNc0pkUW1ueWZKeHY5RDJaX2ZaOThUcWtEZmUwc1JvZkJjUG1zZVpEWUlHdjMxS2JBb1VPRGxSUzcxSkZ2dU8zbzBPTk82Y2E3UmUwRXhDRHlBY2ZfcE5QdHFLVnM1UVZRTTB1a1hqRzBnRkRzZmhtVXlYaUVIQW5DWHEzME5vZDVrel80eEF2OXpqcF81VWNhSkJBU1o3d1lOSUN1bEJkdnIxMkt1S1JNOEQ5RG5xb3oxTHRpaEt4ZGFMbUHSAcgBQVVfeXFMUFR1UzJ5TVVfdDZnc2pWTlFXVUZBbVA4cDZLa3d0N3ExV0xJS3RWOFN6dDU4VTk0eUUyM1hTeWtoYVpHd3hocEhpTEdIb3NYa2UxYlR3NWJmZjYzR3pydjNUa3hxSFBXcFV2NFk3V2JCVTBqRndTVFp6S1NqUlVBaUM4X253VHViaXRIS0hEYnl0WTVKWWgyenQ3akd5UnRqWGUzbkZjNktDc0cwUEJiNURxU0JxNkJxZjZWTDhzc0t5cS1QOVprc2E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "cryptos.tv",
      "title": "Економіст попередив про новий стрибок долара: за яких умов курс перевищить 46 гривень - cryptos.tv",
      "excerpt": "Згадка у виданні cryptos.tv",
      "date": "2 серпня 2026",
      "dateTS": 1785665400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE1ab3pjMTdzWGxNRnZsamZCdDl0MGNFT05nc0JRQXh2YnJUSTQzaG1aMm4zLVYwUDJZaDBHYzZFUVU3dEVKR2F1UTBlS3h5SjJuR0gwY19ISnVITlRQWG9IUDR4ZVNUWkVLek50TDZPa2FvTGo1UFRseEpGaEo4eVE?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар готується до нового стрибка: експерт назвав терміни та можливий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "2 серпня 2026",
      "dateTS": 1785654000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOc1NmMWZzQ0VXVVRWR0NHdVVNdFBvSy1ISnZNRG5DYm1RUG5POTJCSGVTR2RSNkJKaWt3QmRudHhBR2tfRDhsc3otN05hSFpvTjNXV0lobExSWkZqMzUwRmxSb1F4QTZ1TXlhY1BYZEZQaHNuei15ODlabDR1SmZrT21pTjRtek1OT1BkUkRLdUhWeS1JeTZGeXE2eG53SFlWZE5tQTh0ekg2bUJaV2lBa21QVDJmWnZY0gG-AUFVX3lxTE44TkxvUzVzQzdQVTc4S3pwb3BQREJpSG42RGRmTWFpbVhFYUdVOTB1RmMzeWlnNWljN185UElMVGptMHZvZm5QdDFaQXVnVFQzSHI2anF2NUk1ZTd3b1BoZF9zOXRIbC1lV0RxV1FIbENGTEVQRkxzUVRsLV9kOWhselBaLUdERXVjNEdlMmV2dXlIZmxZNkJEZFhMcGpjd3UzTzBIZmhORXpKSjgtZkg0cUYzc1ZfT0ctSVBWZ1E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "В Україні очікують новий стрибок цін: економіст назвав головні причини інфляції у серпні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "2 серпня 2026",
      "dateTS": 1785654000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxPOUZYNVVGaHdWNUtQN0VRRWRlblNUU1ZXTEVsbVhXcEdKcUVqUXZrTUxnXzZQZnlvbDZrTlZ5VTE2dHhBQWE0bnQ4TXlnY0hPUEtrQWtqUXEtWnBxbTNpUVNNZTBMdVRjNGdOSnVwYW1VaHhvTEJJNUlFWE9tWU9PRG5KNUlnWUZ6cUtTSzZLdmh0NVY1Y0NVcktOSVVwUHhDeVpYcDJKb3BkWDRwTFM2djIxWTFNdFhmYlZNRVJrVTRwYVhzZjBhbXZnVznSAdIBQVVfeXFMTUhMR01GTzMxSFVtRnU1elB0V3JWaV9qOGRzWlRDVE5vampFVVRXcWx3NFBza0F3MzlXSHg0X09pdkNKd21QQ3R5OEI2ZHlBQmZKRnFYOTZQenJOelczUnRzUDdFeXN3TWVhOHFXVGZaM053VldEYzVVQ1psbzdUUmpMck84TkF2TElCRTdjaVhBWHphd3RwOEZra0ZVSTcyb1FWdzVFN1lHc1JISGhsN013bW1iVnVud3YtbUc3QlpHVlpPc18xTDdiTzB6V1NvRDFB?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Водіїв попередили про новий стрибок цін на пальне: названо терміни - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "1 серпня 2026",
      "dateTS": 1785609763.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxOS0doR2k0Y1dxMUpaTHpXbXVySzcwTkpwRVdjTXJvWmdlbDhOUjg0N1NQMFg5NVlWeE9qcW91UFgwNFhGaDh4dkVxWlpoY0NXamg3a1NEU0dxTVNsUnY4ZGhhZTFpdDc5cDF2Z3pkQTFKcG0zRmpWTms3VGRlc2ZXV2xkaVgzS1Z3YmZFdXZRSkVsMGd6eU1jV1JqYm1xeHY1c0pmTGxVMXBXQlo4ZV9B0gGvAUFVX3lxTE5LR2hHaTRjV3ExSlpMeldtdXJLNzBOSnBFV2NNcm9aZ2VsOE5SODQ3U1AwWDk1WVZ4T2pxb3VQWDA0WEZoOHh2RXFaWmhjQ1dqaDdrU0RTR3FNU2xSdjhkaGFlMWl0NzlwMXZnemRBMUpwbTNGalZOazdUZGVzZldXbGRpWDNLVndiZkV1dlFKRWwwZ3p5TWNXUmpibXF4djVzSmZMbFUxcFdCWjhlX0E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Долар може зрости до 46 гривень: економісти пояснили, що буде з курсом у серпні - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "1 серпня 2026",
      "dateTS": 1785567971.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxQRmdiUHdtalcxdUVUOGkwLUVNV1V2RWVuZV90Ukh5U25qYUFvM3RvNW94Sl80SEtKamdvdmRvRW81RHlnU0UwN2tVRXprR1JKemt6YnUzUGNheVZWT3lxMnFqWjVDb2djelBxM01HbGt6UXRyTWJSMDdLbzhDOHpnM0lOQzVqYWlzWWRkRHFWa0R5eFBFRllQVWJkZnF1clZWR1FuUWVVWC1WQ0lqUm5rQV9QdmRGa05jV3FzalRWbUFmTl82SXpJYXB5aG9vUXVjV1o4emVKLXQxaHRzVnJQc1Q0NENoZHJSWHROUEZJMmlfbDg3NkHSAfcBQVVfeXFMT01rSjFyQkdKUkhCaUJGNDU4TW82aGo2VS1KMEtCMmNZTEE2cnlWWjFZU191UFNYSF9UaHcybDE2Tjlkd0hmODh5RzVTRU5LLVM4TmlfaWdCTHBlUGhEcFdoTUgyX2hncnJ5R25VcnBRaWhYZTVlVThzM0RBTzhEYmNpZFotbWpOcnFIT2tYcERURk5wOHdmRng2RFhuRDE2MjdfVm1vMU1PdFNINFlQeDZuZlNjNDk5SDhZWUxnSlpuZS1vV1ItSnZYWW9MS2F5M0RobzExSkNxc291UWN3UDVCMEoxYnUtUmFHU2dTeUtrdGhEQkhTNA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Радіо ТРЕК",
      "title": "Долар може сягнути 46 гривень: економісти озвучили прогноз на серпень - Радіо ТРЕК",
      "excerpt": "Згадка у виданні Радіо ТРЕК",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNbzRVR1ROTEhyR0R5SXFWcmt5MkxQdGJpWUE4eWMteDUzNkJMSVNWQzktaGpXaHc5QmZoLXpHcUgwRnp1Q2o2elBqYUxtWVV0N1NZTWVqOWdva2QzM1c5d2JCQXFaTk5weWtidWt4LTZJRDdzZHBnZy1YN0hoOTRjTmQzTHI4R0FycDVSWEpVVU5IcnRNTWptNzBNMXF3TnFOb0V5RmNzcllUWUVVbjUw0gGuAUFVX3lxTE5FYmh5TEZVVFA0NnlXWkl5dHB1SVZVVGx1Z2JWSFZiUjhvWFpBR3lfc0l6N2hBZlJkd1ZVSFJ3MFJJMlpOZTI2RThfbUduUXRuUER6T3FabmQ4UWhla3Raa1J2NVFDbGNRcm9DeHBkQS1YWjFhcVZuTUFXelNoSHBEUGRUaVZwVmxNc2I3TVBIaDA2cS1GZDJnZTEzYy1zWjlUaklLRWduRW94bG9PQQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Дизель може здорожчати до 100 грн за літр: фінансовий аналітик пояснив причини - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQUEdpUUk5cE5XT3RzbXlBSFhKc1loYmpmZDdrM1AxNDlRdGJyVGJhVXFuZ0plNmJfR1hibmxDOUtaeFlCOWJkVXdWZXlYNVFLOXl5dVhZWHdSemJJdVgxeWJ0eVVSOXM5b2sxemExOFlWbEp3Uk9HT014N0hnYm0zYTgxbnhRTFVCRC1uMFVsYlNXMmxJdUhhQ2FfaWNxNkJsd3FVSTM4elNmalR4Qnh0ZlF1ckcxd3li0gG-AUFVX3lxTE4tQXR6TF90UFBsNm1vb055clpKU3o3TVEwR2V6SUhzS3lIazVqank0NTlWT2xaQmN6QTdOU3pVVU1PaWNsNGdiV1Z3OFRXRVJTVVQwazVlX1NBNTRoSHYtamVqbS1xNjRRYXA3YVRJY3VNY2Z6UVhMNmNFNEZRQzVFWERnXzNhTWpaRzhKNzB2bi1JOG5vQkNiNXE3QTJERnlJVTNhMUdTVUxDdThkSlFvX2ZiV3p4WmV0RUZmVnc?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Новини.Live",
      "title": "Найближчими днями ціни на дизель можуть сягнути 100 грн за літр: експерт назвав причину - Новини.Live",
      "excerpt": "Згадка у виданні Новини.Live",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxOS2JhOE05M3pjYU5WejkxelRiMW1lZGJhNS1RNEFMOGEzRjJfRUs4MDNUTGpKYjA2UkpHTlVHS1d0MDcyOWNwdk0xOENKalFzWHdtVS1sTnF5UlB0b1Y5X2xETUF6NXpCY19Ya1M1M3J5QjJzYnkySUFydlBOMC0ybWZ6TXF5dFoxYmxSVlg1YWRkWWFGN1hOZHNtN0YxS0ZFYUZ2YU5pSVVFdWxGd0FsSnFpNmV3cTNfM1hnNlI4eVotX29jdUpz0gHMAUFVX3lxTE02UWsybEJSMW0yWG1pMHdWbThOa3hQdGxrU3pzS2pUb3JoTTVUT0liZnZQVDZfZlIyQmRGZkRhVGZ6cHQzSWl5eGJkVDFfOHlGOWxzRjRzbVhBaTNsTGllek5WdUR1NUw4VEZ0YUhVU1lmQWNDR2Y1ZERKWFp4UlJGb0N5OUF1bUpDMURqX0JxLTVGNUZpMkdCZ3RUSjAtcEx1eVJKWl9YTXpnTmFSaVBDdlJmRDFNNXdsaDNYY0R4RnR1N2ZHOXFMRjU4WA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Водіїв попередили про новий стрибок цін на пальне: названо точні терміни - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNaEEwU1FXdEd4VDhlUmRQME5TaFRjWGFBcmRBa1E0MUF4RTFncjZDUDVCNlJBSWRCNVUxeUZndnM3MHdDaWJKTURZNl93c28xNm42LWc1MkZ1WjNEMjFNZFJLWGQzOU9nSzFxSmllck5tLVdUY2tyTEQwaVJJbUFsYVdoa2lGVi1IbXRmZVBmYU5DWDUxbVlfU1lYMzIzWDQ2MmdRRk9TQW5mUdIBrwFBVV95cUxOS0doR2k0Y1dxMUpaTHpXbXVySzcwTkpwRVdjTXJvWmdlbDhOUjg0N1NQMFg5NVlWeE9qcW91UFgwNFhGaDh4dkVxWlpoY0NXamg3a1NEU0dxTVNsUnY4ZGhhZTFpdDc5cDF2Z3pkQTFKcG0zRmpWTms3VGRlc2ZXV2xkaVgzS1Z3YmZFdXZRSkVsMGd6eU1jV1JqYm1xeHY1c0pmTGxVMXBXQlo4ZV9B?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Долар може зрости до 46 гривень: економісти пояснили, що буде з курсом у серпні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxPb1dYejlrOUpYaDdnMjZCSWJ0b2Q0UFRJeXhiSXFWbXJBY0hQbFJpaDUyTThGMlJJWFd0QU9rdzBfTWpZeDVYOW5Xbk5UbXZWOElUUXFndzJ6cS1acExoaUpFTVdiNEJ5Znl6U1RLNF9tQ2YwQ3Nfb3F5c0tTU1A3TXpHbVNFcmI3WjZHX1FkVnFVRFA3TUktcWhsRi1EbTVMenl2QUZsN2dDZGpEQ3pHelc0bG1SSTB6cUHSAb8BQVVfeXFMUDBXSkdkWkxncE96c25vdmtMTnlEN3JBRmNLNnZUY1ZnVmxDbzhIZ01UamVfME5yaGtaaF9GWWN5dFNtT2poVnBtQzloLVl5UUJCTU5DZ2loUng5dUZBcUwwNnRNS1VwdEhWcDBUWUE5NnhuSldhUmxydDB3Z2tDcHA4alQ1ckk3d2ZDRlhSVm1yeUZYTnczY2FGaXM3RVN2SUg5eDhac090ZWRVd3hZb016TXkxTUFDa2NJVnV0LUk?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Катастрофа з бензином, дорогий долар і висока інфляція: експерти ошелешили екопрогнозом на серпень 2026 - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "31 липня 2026",
      "dateTS": 1785481200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxPLTB0N0pWZVNsQWh0aVNWa1FqRXFBSHlWbkVScVVMLWx4d2p2NWhSUExwS2xjc0tSbXRTYk55YUJlZkdIT1VMQmV3X3gzcE1FalplbmVkalBMZzRIOGl1R18tYW8xNHVnMnEya1R4ZE5RM3hvVnFqV3NLN1hKS1Bmbno2MG1Db3ZwWkVrNDRLWjNwYlhrOThCV2JONTExSFBhMERkdlVwQXZUVjFRTExrTnZGVzJRdDQ0RDIzM3IwZWl4dmFZdjJieUdpTdIB0AFBVV95cUxQbUUzaGx5WHMzWmNTcXYyQVhOWGpMVjNpaUkxTlBkdG1uWldoQzhOMjF3TXRnVnRUdWV3a21xMFNHUDRNam9mY3RFRXJVcHFDeVdyaVd0Q2RnN0lyV1BsWVhuX3ZubzVST3YxbWxESGpfbDdSMUlodktlamxaaDJ2Q1JWZ2J1MDU4NnFPemVYT0l6dnFzalY1dmdDdlVja2VTNWJxZllZcjBNaTVUOURpVTQ3YUt0ZEZrdXBUUnhkajcwQVdhamRqbHBHNkdtdURI?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Minfin.com.ua",
      "title": "Чи може підвищення Нацбанком облікової ставки стримати ослаблення гривні - Minfin.com.ua",
      "excerpt": "Згадка у виданні Minfin.com.ua",
      "date": "30 липня 2026",
      "dateTS": 1785394800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQM1RwLTNFVUZYODlVOWlrRE1maGEzR2JLX3pKdU5lWDVyNjNXZUZ3UHZ4eEJSWVhRbERvUmo5eFd0V3JJZ0Q5X2JGYlJHME9qYUJWQ05sWVNhOEl5Q3E4T1BxdHlnMVBlN09HWDJOeHpiVE5sYklYSUNsTm1nNnFTYnFzcE1sdDBJbWRoWlV6U3hENGo2RHhGMmMyUnBYSEl6dmZRUzJaSzJHZ1pHdmdfZU9kRmEzN3pO?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "РБК-Україна",
      "title": "Удари по Wildberries можуть вартувати продавцям РФ до 1,3 млрд доларів, – аналітик - РБК-Україна",
      "excerpt": "Згадка у виданні РБК-Україна",
      "date": "29 липня 2026",
      "dateTS": 1785308400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxORW1CWVFVMmkyTzd5NUc4VUZDY3FBWWZWMmRNMXBVMWNLbXdWd0lRTV85MEtDSlk1WHVvak1WRVBHQm1La2NxM2FnUWUwUEV5UkZRcjNwRk1JSThWTE5DbEZMdUU2ZGN0NUJoR2s0ZTlRME5SZjlPUGFXRml1Y2tsancycThyN2ZuMnRodzl4Um00Wk9C?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "РБК-Україна",
      "title": "Удари по Wildberries можуть вартувати продавцям РФ до 1,3 млрд доларів, – аналітик - РБК-Україна",
      "excerpt": "Згадка у виданні РБК-Україна",
      "date": "29 липня 2026",
      "dateTS": 1785308400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxORW1CWVFVMmkyTzd5NUc4VUZDY3FBWWZWMmRNMXBVMWNLbXdWd0lRTV85MEtDSlk1WHVvak1WRVBHQm1La2NxM2FnUWUwUEV5UkZRcjNwRk1JSThWTE5DbEZMdUU2ZGN0NUJoR2s0ZTlRME5SZjlPUGFXRml1Y2tsancycThyN2ZuMnRodzl4Um00Wk9C0gGaAUFVX3lxTFBHY3BUaExjRk9vRTRFeDNFdXBsaGdvbktrZi1KYzdRaHNRcHFSODFyQjh5d18wSEhxZTYwM1d4VTR6d1hSZFVySm5BOVo2aW04eGV5NmhQU3daSlFEVEJwRzRTb0lJT285VUNRTkpiNFZ2UnVlS2kybVZlVjBDZkVPbE1fLVdwNDZfdHlBblVXT2tZXzU5QktRWFE?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Блокування українських портів: що буде з гривнею, паливом і цінами - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "24 липня 2026",
      "dateTS": 1784876400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxQUGVGcGdpZVBMUGkzV05DUG1hNHhGamMxclpFaTlKUHZxcXE1SVhnSTA4aldCYUtzYzlxckJiQ0FKNV9tWDZZNnV3VlpxTzJWZnNDbk5zR3dtNktKUUdtdnY2eEVJa3dNZG4zazNLRVZCcWhkQ051UGUxUUFGR0lvUk0yRXVKTG1jLUE3STNXUm5sVm05RGQ4SW8zOGZ5b3ZFaEI4MzBXUlQyX1lUcDFzUU9ZZmJXWjB3TTlQNNIBwgFBVV95cUxORVJ1YTFRUV9aeTdrRmd6NUItT1J4SDVTcksyZVcyVDZQOThDY0o2YlBoaERJUXJJc2hXalFPZG1iT0s3OHROdUF3SEtnYkE4dk55NFYwYzFOQjdwSFJxdlZNLS1CaDlLdlYxNy12bFBXUFBuMVpuQzlfb2dWSE1FRENIVGtSMnVVMlpkazVkUFprdDlqU3R1OHZVN2hpdFdBQ3NHeG1aRXJvYlRuMW9kUlpHRGpaTWZtc0pvZkdJeHBQZw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "УНІАН",
      "title": "Зростання долара та подорожчання низки товарів: аналітик про наслідки закриття портів - УНІАН",
      "excerpt": "Згадка у виданні УНІАН",
      "date": "23 липня 2026",
      "dateTS": 1784820480.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPb0VHcWs2OUc4bHJjTTJNSkhNVWFld0toNUJRUHp4ZkdpbmJBak9ZVlY2bGgwcl9ZaWlCLTNGeE5TMnZnV2hiRklWVHVjRTBUVm5qZl9STGxSeEtESkJLaFJFUW1WUERZMDEyQjV3MXY5RldyRVRETl9rd19SNlpxOXMtWDE3cVE2TkVPbjNlWGh1V3ktWHVkQnh4QnJsWHFaM2swek4xTUI5Y3RITUFna2t0RWstZ9IB0AFBVV95cUxQRGJnWWxDQVhNbkFYaGdpY29Bam9VcW9vTnNEYXBjMTRIbFZ3VDcwRnN6NmMtdzQwZWVHZkhrNlV6VVlHNWIxdzBiSlllS1hTVm9VTXRRdllXZ2oxR3MzWmNRTmZlRDFuclhEWG16eHhfMmdQTzdid01vTmhFRC1LZzJQdUN5ZW1XdXJoNlVzR3hNQXA5WGtxaWpqQm95c0xYRS05MTFYNXBGdWtiM1dyZlUtN3lxZWpVZnJDRUFoMzY5RGE2am01aUszOW1mY3Nn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Ціни на товари та продукти підскочать: розкрито, що подорожчає в першу чергу - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "23 липня 2026",
      "dateTS": 1784790000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxQaGNxalgtT2ZpRVpNTi1ZVmcybm05ei1CSHY1azBDbGlFQnpPUGEzMzZpRXVURHR2c1FDcnVEZUE1dHlwc1NHVUoxdGY4bFZkZWRpaHRNRVI3TUlUdmJuczJCWnlPYUllLUVhMEVfcS1Ma2hmN2xSQmM3RFJtYUZFaDloRjVZV1U2UE5KX09kYzVOUFNzLVJaS0QzYnJySjc0YmdOZXVQMjRhb3R3NE5BdXFFbUdTX0g1OUlVaTFmVXpTQdIBxwFBVV95cUxQLXdJRm5xRElGSkY1dzc1X0hIR0JLLUJPODVnLUkxTnBudDc0M3p6RV9meVU3WEd2UDdrTzFYaUpZUGhtOUdhM0R0d2hpMFBPN3hUbnd1MmNTWGlfcVJEaVpxMWc3eWl5b1VnMmRMc3VSYl9VM051V0ZBTC1mSUQ5S0paZ25pWF9Wekd0elFiUEhCWGZIMV8tNlVSWWhHeDNQa09WNjU0RjU4Ynk2NEVQcDdDVkEyMFY5OUdDTGxtRjdiSTZGcDJF?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Українці відмовляються від долара: економіст дав пораду, яку валюту краще купувати, а яку — продавати - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "20 липня 2026",
      "dateTS": 1784542739.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxQM3lieGx2ci04QXl6VzVaSEtaTVdBb0NVOWRKcE9ScDdyZmh4VkstQmY0dlJWVDEtVkU5Ty1tM0lldkctV0RuUzBIMl9VSkdlYjlNY2hMVnJEZGh4aXptLUR4Mm5Md05hS25pdXhWTXZqeFFLbmgyQV9ueXVpcTZES1hwWmZKbWptUFlMY0t0cU5ScWhjc0ctNDIwWktmZzhwY1M0OFlEN0tpOG5mQXV2N2R1Z1RQaU1MZzZfUThYWk1vdGp6VHBRZTBlbm5rSm1vcWdYQkJLMTdtWHFC0gHiAUFVX3lxTE9ac0hYb2NfUW0xS0VrVW1ZTllUQU9mbDkwcV9oaDRKcFBNb0UyUXFYTUZIN0V5ZkhVS21VUU9zUUhfUTRRNWZhRXAzU2oxcVFURnZPLXdFaE5lOUVPUEk2c01vcklpS0xjRzJhLVBUdExGU1NVeFFDTVJxVkRGdFhYZnhMcVl6VHRIYTNSTWFzcVpoeXFINDluS3V2Vlp4MlFBMkQ3NEhDVWp6QzRIUFQwV0p3ZklOam5wU0lmaUl4M0xBTDdKU3hxR0ItNzJ5UEdkZDYxTTgwRUR6Slk5OV9tUXc?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Курс долара готує несподіванки: економісти ошелешили, що чекає на гривню найближчим часом - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "17 липня 2026",
      "dateTS": 1784257572.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMikAJBVV95cUxOUmNoWDNva2Rvdnl6X3BGbFFXWFNaR3lpZVpxZm51Z19CdkpSaklFUl94bVVwdEtmUUthd2ZCZ1A1c2hzMXBjVFF5MlJpVzZWd0pwekFWU0J2VzFNQUVIYlNFY1h2RlBMZTI4WEhENjBJdHgwOExEWWVrV25UdkZ5VjZNY193NnB5WW9CVVBTcGVoRm1tZlJ5OGF4bkFjWU5KSktXeE40SzYtbEd0WlJHQXZzdW9CcGhWalFoeURROUFtSEozZUR0R1FuOFVTWjNUcy1ITGo2SE93a0Q4NE40SzFGMUFodERsTWdoM0JmNjZkbGU1djBycUh1dllEd2tKNS01UGRQTXpySHBwQU1DWtIBkgJBVV95cUxPYkdCNVIxbUVfTWdvRlhJdWNzY2NJQXBLUDAtYklfZ2RmUXpfQWJlMVk4VUpfNEg3Tm1NWG5sb0F4aDRlYU1IUHZRajVwbnpIVklJeHVZVEJhSi10SXJnbUV2cTNScW9fU09RTURIMWNrUWU1SXNoMXg0dVNGT1ZWZ1hmR1dlMU5fTTE2RlViZ1lycl9FeG1oQlBtWk5ZN0tUUWxvS2lnVXVPMjRjZ1hfUzQ1eXV2ODBEX2xYdEtlMVU2RENZdjVBVTBNS0R2ZWFFMjU5RkNzN1BSWkpDV3hCX0xlOF85aXdIQ0s0bW5uczlablZiZ3d3UzV6RlR1bjRQRjFkejVtZUc0b1p6SDM1NXVn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Курс валют в Україні: реванш долара та \"пастка\" для покупців євро - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "16 липня 2026",
      "dateTS": 1784185200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQc3BvVmZHd18xYVZlVllkR21mSWxwczZpWjVwYXlpNTNnVDJudWdDWDBnR1puODNGaVEwQWpjYTd1Y1JGX2ZUdi1SRmVvWk9naUJNNnl4dmRrb0FOWmFadTVoaVhVbUJxTjkxdDhoQjd6OF9vSVgzbFdKVUluTXFnYmxUd0NvRFloOTNMV3hTcFl0NW1DbGN6V0QtVm1RYTBwNF91X2dPQnRVd9IBrwFBVV95cUxOUXVaSlRvSDgxZklXN0ljM3BiNExUeFk1dlBkREJWZ204MTJkSnJmLUJTcnZfVTVaMUhCUUxNSFhzOG9qQ1IxX0tIRXkxejBWeFdZUloyRW1jQVZidS1VSFlRYWd2MWFnS1BwblVfLUNwZ192c25LYzNHbEYzc3BEZkl3Z09wQkRSQkx0VHBYRzBsNllmQ2kzd2NYSUNjaGVuTXhEcU9ZSTc1dDVTb2NB?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Які наслідки для українців матиме підвищення тарифів на проїзд у Києві — експерт попередив - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "14 липня 2026",
      "dateTS": 1784050572.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxQWUhneEQ2Y2d4ZExqeTZiWndhbGk0YUhNWF9uQ2prdjZVM2tMeEtueFNrZGNvQm9rYUpJNkgzQVpNR2lMZTI1MGJtY2ZqVHBLTTJrR1VLeHNzcDhYRWN6MndiZGZpeldnak5yZkdxOTN4VHlqSE9RUDRVanhiWXZSYnlfLW5BMmVnX2VXN2k2RGZFdC1NVmdaNTMtb1B6VGExWUhkZFpNc1VHenl4UUFTMmRzendBdllVU2lXdkttTEhDdEJMUDJvQm15ZTVncEtHdHM1emJlUk5fRm_SAY4CQVVfeXFMTW1XT0FvWDlFYmxKRUUzMkI4LWFoS3pQZFVRSEFlMEd6cDJ2LWhiaFlkNjZDZE9RYzBabEo2Wk5hZGFUb1N4M2ZYdXhJdy1vNmFfZjc4MkpELThaNk9USHVXZmdsRnhOSVgzM3NwQmV6ZWE4NGNNVC15TlBxb3JEMFpFM2VuUXc2U29BczY3dU8xNlRXUHRCT3VYdTZYanNYeFhPVWZDelJYdmNsbEJ2cWo3WG1sRm0zT2hPYnZnb0hsRDFQb0JKSzVPeXBpWVZDcjZ0cUpzRkk1Mll6bmdXREZ0SGZzbWZlbWNrT190V2M1VUYydFR6WlJvWEtqdDBOMEhmbmtuU1BwSDdCaFNn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "УНІАН",
      "title": "Усе стане дорожчим: аналітик попередив про неочевидні наслідки підняття цін на проїзд у Києві - УНІАН",
      "excerpt": "Згадка у виданні УНІАН",
      "date": "14 липня 2026",
      "dateTS": 1784012400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQNHZ6SkExSXBxaEZ2ckZuOXU5alJvMkZtdU1xNFRhTU5lcGRUd3lHQTJOMkFuZXZkRWlfaUxsUThLVUpCekZOYmNsbHd3dVlvT0pEOUFGR3JidFpTMEJWQlpuYTlKb3R0c2ltbFhjS1FIYnI3Z3BONXJJaFIwcHR3Y3pXaUN2enNKWlVUa2Q0X0hLa1JISFg0VjBBRHVuanUwZ1hwRmc5SmxHZ2VRcktOM3hvcmMzMHhNNE9DZmNIWWFVRTQ5TG1oYjBiVjFjdDEwSlBfdWFB0gHbAUFVX3lxTE9rSjdBXzhKdHNhdXZjMHdaeHJfa3ZNUkZQaE95QmdPaWl3NEdKUkFrdjZtaG91d2h0ZmgwOEtlQnNLczJ5dUpZTnRXdWdrYTZBNnFJeUhwaWdsbUhBbmhyU2VyZ3FJa24welE0U25QMGg3TlJWVjZROG9UR1dXUVhRckN5MTJvX1dGdUJnbDREekRkdDB6anhPN0g3SEJMUFBVVzAtYjJaWGtEQktKOTJESWVrOUMzSElEVEZ3OWNHd3lGY2FPbmFnRzZ0Szg1VHRfZlF4YThfSW5zNA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "НБУ почав не лише продавати, а й купувати валюту: що буде з курсом долара - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "13 липня 2026",
      "dateTS": 1783931237.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxQRUwxanl3U0xMN2p2ZVZJVlN4X3FkaTNRV2lrOVZWbVF1bDBkeDVXZVdpZHhKU3BlbHNxZHpJNVA2SEtiNXM3LUhTbkF2S1drYTN6YnVWeXdNOTJncTlpUTAxSjQyeHVfT2RYcS1sazNpRmdhQ2lubk9CQy1odFR5M3BsNnRKZ0t6TmhDZVoyYVMtTnBjZnVnbllxQTB1S3ExaHBoNFJYTTYzUkUxS19nMEtFSVA2ZmdMcXfSAbsBQVVfeXFMTy14Y09CVFZRQmtvdFZ1aWx4V3NlUTJnOVdpZFVTekZDTkxkWHdqTDVZQkVSOFd5WkpzZXRHcTB1aTlRVUJCOVZjWXlZYWJtU0R4SU53Ni1JZDFSY1hOclBTS0MxRHc0QnFiZGJMSlhUWTk1NUI2UThpRUVPQXJjZUMyNFA2MWl2ejl6NHlJX2Y0RklGUUkyaHVuQXM2SkgtR1lTY0g0cDNVb3dnRFBUZ0U5YmtIdmhrTHpicw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Це історичний рекорд: митниця показала, звідки Україна найбільше завозить техніку і транспорт - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "9 липня 2026",
      "dateTS": 1783580400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPX1BqS0NQNTVBUnRGaHV5VHhlZEg3UExrUUxpcVdyZi0td1ZNdTFBZTl5R3ZodjFDdW02YnZqZWNpbldzSXZjTFJDaHdaV0pFclhTV0hwS3hUNEpzU1l4Tm91QkxuYm9nT2ExVWhMQS1ZaDBKbUVJSW5VU3dqem1GbTF5U2s5V0tBbWdsckZkcVVQekQwZ01WYVh4Q05FR1pzLUF4TjduS2tYQ0lHWldxcG9ub9IBuAFBVV95cUxQZ0x1Ty1NZEw0U1RlcElzWEV6WGx2c1BCOHA1RmxIQjRjaWpncmlCMl9vczQ0bkNIcGxpRFAyakpJampvbDVZeThLNTJuZWcwXzdyVDZzXzhKRzRWSmc5NWZvNWlTNzN1b1ZxZXV6Njl3djl5VWl0NnRrRE50SUZHY3Rrc0JDZVd5YkNUTDNpdGc5VDdtRXpIM2gxRTFYY3BCR2g3NnhJVXRPX01wVTdtMmZaZlhvQzJk?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Курс валют на 9 липня: скільки коштують долар, євро та злотий - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "9 липня 2026",
      "dateTS": 1783569976.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxNck5FZkRTSm5RSEFIaTN1TW5ucGoxSTZRTGRfaDdkdy12dmljVV9PWmpQd05wSTJvQnlEOFlvSWM0TWUwTk5pRHdrWWl6eS1YcUZyNDJZSGdKM1RERThuTUR5bUdIX0Z4OXdGRll2U0dScWpwQnMydzRIWWZwWXhkQ1gtQlY1SHFJVDZEMlI0RUlaYmVFX0hYM2ZIT05DNHp1M3lxck5yd2FydEtWNl9YTGtmY2RRc3Y4OWVzZVhWYWpZbE9KNFpGdjNDMFZZMjdiSFHSAdMBQVVfeXFMUGdSbGUzYjQ2RjBQSF9aRndjTEFEbDJiT3ZBVEJSRUhxZGV0X2F4TF9ucnlwLVpRZWxjb2djYVdoQlpCT0JMMC1nMHNnaERsdEltR0VtMzNWSnZXZUZMODNSWl9CX0ZFZUJZc3lFaXdxV0ppbDg0UExIUmFJTUh2RVA5U0lUV0Q2emFNQWVVU2VYbnFTOVRIQU90ZzB1M0lSRHNFdWxBTmVlOXNjaF94Q2JrcGdGNTNpZ3MwaG9wYzBmUmJ6WWswcTh4RlZSXzhOUFc4UQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "UKR.NET",
      "title": "Попит на євро серед українців побив історичний рекорд - UKR.NET",
      "excerpt": "Згадка у виданні UKR.NET",
      "date": "7 липня 2026",
      "dateTS": 1783450266.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFB3S0o4UDdYUlNDSTUzVDR5NkIzbTV3T3RaY1ZkbE1QbkdiYzNJSFhLcHNwcG5hNnFmYW4zMG9tZnpZbGVoa21aSDE2R3c3a21GdWdXV1BNQnI1SW1VUV9rd2NlSlM3dUJl?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Кому підвищать зарплати і пенсії у липні: експерти ошелешили прогнозом - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "30 червня 2026",
      "dateTS": 1782802800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxPekc0M2pINnlzeGxZbkYyMEx4MUdBYklVUWhJcndyTllOOUdrMGQwd0dmNnN6UGFiNU1FLXVIdjR3WHZ5eUN4RDlEeVNxazRBb2dZNm5rbkRKZ1lpckdkeWdGRDFxYWxvejQwWm4zMmdHcWlZTXAtU0Y4UXFnelZRcDVoNXNlM2V6M1hCOXQ4SGNRa0NDLVNiY2dyak5HZVBsaGNpX2hKUnJIaVh2NGZDa1NRZnMtZU9iQndxa3MxS18xdlU3ZnJ5MjNBUHBFVGtIZ2Uwa1RwMFFHZ1RkN0t3cjdmMUJtTHo50gHqAUFVX3lxTE5KMUtrcHNtTEJCdHlpNzcxUFZJUDlTVkNTUmdCVUhMeDlTbVdNN0dsczlSZjVuckQ3SFNNdUpuWks3eHRZMVhPOElhWnphMkl0RFVNQlpJd0NCNXp2M28tXzFIeFdVOHF3QUxoZkJlWkFSeHhRVnR6TkdUY1RIX1BHcGhqV3plQ3NqalNVcmZNSVRhYWZUdnNJeFZrMVBhLWFUelRyRS04SnNDSkk0SkdnLWhfZUxXNmRuaUM2eDEyTFRVcW1oY2VkMEpQWkdqczVITlZ3YTFoYlpreTFCWFI3QVVRSnpxcVJvZw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Minfin.com.ua",
      "title": "У травні українці масово продавали золоті злитки, але скуповували безготівкове золото - Minfin.com.ua",
      "excerpt": "Згадка у виданні Minfin.com.ua",
      "date": "28 червня 2026",
      "dateTS": 1782630000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFBTbnVVdXc4VUR5ZGEyNFBub2ZacnJLalZlLUptRElKQ0hOSXJBZWlfQmhXcG8xazBESGl5VVZNZE1iUGlwaTdnWUxwQUUwa3d0NkRmLVJNSHpGUQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "\"Утримувати 45 грн нескінченно неможливо\": яким буде курс долара у липні — прогноз експерта - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "28 червня 2026",
      "dateTS": 1782630000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxNM0o5UlUtcEZPSkgtaWtrTFBoMUdRN09LR2FpMXJnSkRGTHVSb3lsTHNjZm1lQ3pEamRKUDF1Z2hNX1M5UmNJQkltMGZkZTNPMWJ3cVB3X0M2S1hPZUZmc3A5TXo2VHdWOFFLaXY2X0tEaE1LNWt3Q1BBMGw2TmQtSDNjdUhBeWxLS0k5WTR0TG1Ua1RNX3o3S1JTa1BQSmEyejBr0gGoAUFVX3lxTE41VlI5dTBLZjVSaGV1YmRvOW9LRndjZDJPMFJfM3RERmpmLThnRkxQaHhkblQyNk44MkVUaUZqRTN3U1FfWF9fMGw2Mmg2UWpXLVdMTVpkbThvbDRzY0h1TjBxSFVEczdkaEFjREZvN09xRklOR3R6NGRMUmxLU2Z4dE5iMmVvOUFOWUNsVHU0d2FraXJWQXAwTVJhdElhUkNxTnVqWWNKQQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Сценарій миру вже у НБУ: експерт звернув увагу на важливий сигнал після рішення про ставку 15% - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "19 червня 2026",
      "dateTS": 1781852400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxNMHN6U3pScGVsQUwwanBkWWF0Y19keGstUlBybGRHa3diRGtBcjduS0YyQU9mSmlCUk4tckczb2RiVy16X0dJYlNHdzhFVjF4VnFtVkd5Wks0dGpxc1hSZFEyUDR3UmdyQWdVODBmczV4UTlYckFxdVlzelZ0ZDFQSW1VMjBaam9maS1YT0thcWJ3UkJycHBDMFlvR2xIQ01ZNlV2ZnNUdGY4aFRBZEVDSE5DRVYxVk1yclZTNG94bEPSAcYBQVVfeXFMTVhYdTV4OWlZVkd4LWt0UXY5RUpheDZkWHJUWU1hNHRDRWx6MHMyUTN3U25RcVlSZkUxcG1fWFBSYTJyM3JvLUxtbk0tUlRyeFlIZ2c4eTM1aUFOWE40a0xqOFRTNWMxMlpETHRKaWFIMWRtTk54WmJCN25DcWN5M0FXR0JZbGE5N3hpNXRUVXhJeDRyMjl0eXFrMWpjZVBTeDJpUUM3YU1BZGM0UFNwMWNyc3ZsNEV2aWRFME02aGtsUm5fQUhR?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Долар шокував ринок, курс валют пробив психологічну межу — фінаналітик зробив прогноз на тиждень - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "15 червня 2026",
      "dateTS": 1781506800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOLUhBbjVXZm95VnVNM3JuYVhOcE42d0p2SkhwRG9FWk1VenhELTBka2ZzMjZEeTlWVkl0XzJEbmU1OFRUYWdOS2k4UGlxdERDUGo2anlqUl9sSlE2VzBfVV9OTmQxSkxoZjRFNklYNUxVMWlTMjByZnJVaTlIWWlOTmY3Y0duLTlPYzhBcVNZclRrRzBUdjBWMU90d3BZdEx5STlwRjZwTHFsdGd1eExPRVJtVUdfMUhE0gG-AUFVX3lxTFB5SkZBVkVpZTBJaTVaeGJneFdEYUp4NUpReXJERFpReU1mQXozZTZ6V0xVenBUT2dpcUduZHo4V04tR2djQVE4QXVjYkEyNHNEYzA3NkpvbWZHTzhNaW1ZMHNTT2FVczMtM1pyUnBoX2FkRFdkdGk5SWVVTG51Q3d1UUtUaWVURk9Vcms1aDRvSlVybWVSaVN3VUhZQUFNSjJPcF94ZUt0N001SmVIendLQ25JbEZsRkg1dFlWUmc?oc=5",
      "external": true,
      "featured": false
    }
  ],
  "youtube": [
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ДОЛЛАР НА ІГЛІ ІНТЕРВЕНЦІЙ НБУ",
      "excerpt": "00:00 Вступ\n00:38 Результати тижня 31сер - 5 вер 2026\n04:02 Баланс ринку \n08:55 Очікування на 7-12 вересня 2026\n11:29 Слідкуємо на тижні\n------\nFacebook: https://www.facebook.com/AndyShev79\nТелеграм:",
      "date": "5 вересня 2026",
      "dateTS": 1788623366.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=SIlOBjFCVeQ",
      "external": true,
      "featured": true
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "БОКОВИК ДОЛАРУ ЗА РАХУНОК ЄВРО Й ІНТЕРВЕНЦІЙ. ВЕРЕСЕНЬ: НЕГАТИВУ БІЛЬШЕ НІЖ ПОЗИТИВУ",
      "excerpt": "00:00 вступ\n00:41 огляд серпня 2026\n06:00 баланс міжбанку\n08:59 готівкові операції населення\n10:00 безготівкові операції населення\n11:25 загальний баланс ринку й інтервенції НБУ\n12:53 очікування на ве",
      "date": "30 серпня 2026",
      "dateTS": 1788106846.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=JFtDELniHpE",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ПІДСУМКИ ЛИПНЯ - БОКОВИК ДОЛАРУ ЗА РАХУНОК ЗНАЧНИХ ІНТЕРВЕНЦІЙ. СЕРПЕНЬ РОЗСТАВИТЬ КРАПКИ НАД «І»",
      "excerpt": "00:00 вступ\n00:45 огляд липня 2026\n03:04 баланс ринку, попит та пропозиція\n07:35 головні події липня для ринку\n13:35 прогноз на серпень: фактори впливу\n18:00 базовий сценарій\n19:35 оптимістичний сцена",
      "date": "3 серпня 2026",
      "dateTS": 1785733234.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=aKwW09CAGas",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ЗУПИНКА ПОРТІВ - ГОЛОВНИЙ НЕГАТИВ ДЛЯ ГРИВНІ. ВСІ СЛІДКУЮТЬ ЗА НБУ, ЯКИЙ ПОКИ ЩЕ ТРИМАЄ ДОЛАР",
      "excerpt": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 20–26 ЛИПНЯ 2026\n---\n00:00 Вступ\n00:41 Результати тижня 20-26 липня\n03:14 Баланс ринку: попит, пропозиція, дефіцит\n07:00 На що звурнув увагу на поточному тижні",
      "date": "25 липня 2026",
      "dateTS": 1784977422.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=tYvAcY3K6Mc",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ФЛЕШБЕКИ ДЛЯ ПОКУПЦІВ ВАЛЮТИ, АЛЕ НБУ ТРИМАЄ РАМКУ ДЛЯ ДОЛАРУ",
      "excerpt": "0:39 Огляд валютного ринку 13-19 липня\n3:15 Баланс ринку, попит та пропозиція, дефіцит, валютні інтервенції\n6:10 На що звернув увагу на тижні\n11:36 Прогноз динаміки курсу на 20-25 липня\n12:52 За чим с",
      "date": "18 липня 2026",
      "dateTS": 1784396204.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=V9y3jXRbAWc",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "НБУ ПОКАЗАВ ДІАПАЗОН КОЛИВАНЬ КУРСУ НА НАЙБЛИЖЧИЙ ЧАС",
      "excerpt": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ\n\n00:38 Що відбулось на тижні 6-10 липня 2026\n02:37 Баланс ринку\n05:40 На що звернув увагу на тижні\n09:45 Очікування на 13-19 липня\n10:57 За чим слідкуємо на тижн",
      "date": "11 липня 2026",
      "dateTS": 1783800069.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=UADE6-VOSfg",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "НБУ ТРОМБУЄ ДОЛАР РЕКОРДНИМИ ІНТЕРВЕНЦІЯМИ. ПОЛІТИКА ЧИ ІНФЛЯЦІЯ? ПЕРЕХОДИМО В БОКОВИК",
      "excerpt": "00:00 вступ\n00:38 що відбувається на валютному ринку\n02:05 чому? політика чи інфляція?\n04:50 баланс ринку, попит та пропозиція, валютні інтервенції\n07:15 на що звернув увагу цього тижня\n10:55 очікуван",
      "date": "4 липня 2026",
      "dateTS": 1783195212.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=a1mVO9GBCd0",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ. ПОПЕРЕДНІ ПІДСУМКИ ЧЕРВНЯ 2026. ТРИ СЦЕНАРІЇ ДЛЯ КУРСУ НА ЛИПЕНЬ 2026.",
      "excerpt": "0:00 Результати червня 2026 загальні тренди\n5:01 Ринок в цифрах: попит, пропозиція, дефіцит, інтервенції НБУ\n9:14 Події червня, яки вплинули чи вплинуть на ринок\n14:06 Три сценарії на липень 2026\n19:5",
      "date": "27 червня 2026",
      "dateTS": 1782587703.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=QTtH3tdFvt0",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ДЕФІЦИТ УКРАЇНСЬКОГО ВАЛЮТНОГО РИНКУ СТРІМКО ЗРОСТАЄ, А НБУ ТРИМАЄ ДОЛАР Й ТИСНЕ НА ЄВРО",
      "excerpt": "00:34 - Що відбулось на ринку\n03:05 - Ринок в цифрах. Міжбанк \n05:11 - Ринок в цифрах. Готівковий ринок\n07:23 - На що звернув увагу на тижні\n12:12 - За чим спостерігаємо на новому тижні\n12:52 - Прогно",
      "date": "20 червня 2026",
      "dateTS": 1781982049.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=k7G6sdoXoNs",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ДОЛАР ПО 45, ЕКСПОРТЕРИ ПРИТРИМУЮТЬ ВАЛЮТУ, НБУ ЗАЛИВАЄ РИНОК ІНТЕРВЕНЦІЯМИ",
      "excerpt": "ВАЛЮТНИЙ РИНОК УКРАЇНИ ЗА ТИЖДЕНЬ: ЕКСПОРТЕРИ ПРИТРИМУЮТЬ ВАЛЮТУ, ДОЛАР 45 НОВИЙ РЕКОРД, НБУ ЗАПІЗНО ЗАЛИВАЄ РИНОК ІНТЕРВЕНЦІЯМИ\n---\nПочитати в FB https://www.facebook.com/AndyShev79 або в ТГ https://",
      "date": "13 червня 2026",
      "dateTS": 1781383209.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=qBrlyuvxcoU",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ ЗА ТИЖДЕНЬ: ДОЛАР НА РЕКОРДНОМУ РІВНІ Й ГОТОВИЙ РУШИТИ ДАЛІ",
      "excerpt": "Почитати на FB https://www.facebook.com/AndyShev79 та ТГ каналі https://t.me/shevchyshyn_trends \n\nЗа перший тиждень червня торгівельна активність українського валютного ринку, як й очікувалось, знизил",
      "date": "7 червня 2026",
      "dateTS": 1780826000.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=DUose7Z5PKk",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ ТРАВНЯ. ТРИ СЦЕНАРІЇ НА ЧЕРВЕНЬ.",
      "excerpt": "ТГ канал: https://t.me/shevchyshyn_trends \nFB: https://www.facebook.com/AndyShev79 \n---\nВАЛЮТНИЙ РИНОК ЗА ТРАВЕНЬ В ЦИФРАХ: \n• ДОЛАР: Долар на міжбанку зріс на 0,4% до 44,26 грн, встановивши новий іст",
      "date": "30 травня 2026",
      "dateTS": 1780155251.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=P_OpERiOWmY",
      "external": true,
      "featured": false
    }
  ]
};

// Поточний активний фільтр
let currentSource = "telegram";
const PAGE_SIZE = 8;
const shownCount = {};

function postCard(post, hasFeatured) {
  return `<a href="${post.url}" class="post-card${post.featured && hasFeatured ? " featured" : ""}"
     target="_blank" rel="noopener">
    <div class="post-tag">${post.tagLabel}</div>
    <div class="post-title">${post.title}</div>
    ${post.excerpt ? `<p class="post-excerpt">${post.excerpt}</p>` : ""}
    <div class="post-meta">${post.date} · ${post.readTime}</div>
  </a>`;
}

function renderPosts(source, reset) {
  currentSource = source;
  if (reset !== false) shownCount[source] = PAGE_SIZE;
  const posts = CONTENT[source] || [];
  const container = document.getElementById("posts-container");
  const moreBtn = document.getElementById("load-more-btn");
  if (!container) return;

  if (posts.length === 0) {
    container.innerHTML = `<p class="no-posts">${typeof t === "function" ? t("posts.empty") : "Публікацій поки немає"}</p>`;
    container.className = "posts-grid";
    if (moreBtn) moreBtn.style.display = "none";
    return;
  }

  const count = shownCount[source] || PAGE_SIZE;
  const visible = posts.slice(0, count);
  const hasFeatured = visible.some(p => p.featured);
  container.className = "posts-grid" + (hasFeatured ? " has-featured" : "");
  container.innerHTML = visible.map(p => postCard(p, hasFeatured)).join("");

  if (moreBtn) {
    const remaining = posts.length - count;
    if (remaining > 0) {
      moreBtn.style.display = "flex";
      const label = typeof t === "function" ? t("posts.more") : "Більше";
      moreBtn.textContent = `${label} (${remaining})`;
    } else {
      moreBtn.style.display = "none";
    }
  }
}

document.addEventListener("DOMContentLoaded", () => {
  renderPosts("telegram");

  document.querySelectorAll(".tab-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");
      renderPosts(btn.dataset.source);
    });
  });

  const moreBtn = document.getElementById("load-more-btn");
  if (moreBtn) {
    moreBtn.addEventListener("click", () => {
      shownCount[currentSource] = (shownCount[currentSource] || PAGE_SIZE) + PAGE_SIZE;
      renderPosts(currentSource, false);
    });
  }
});
