// Автоматично оновлено: 2026-08-15 08:17 UTC
// НЕ редагуй вручну — файл перезаписується GitHub Actions щодня

const CONTENT = {
  "telegram": [
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "За 12 днів серпня, падіння експорту пшениці та ячменю майже на 80%, кукурудзи майже на 60%.  Це н...",
      "excerpt": "",
      "date": "12 серпня 2026",
      "dateTS": 1786540834.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/546",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "💰\"Збитки колосальні\": у Rozetka назвали вартість зруйнованого Росією складу.  Зруйнований російсь...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786466547.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/545",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Тут без коментарів. Суд та ДБР мають надати свої висновки.  Але здається, що без ніякого попередн...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786450102.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/544",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ДБР открыло дело о подделке диплома Пышного  Шевченковский райсуд Киева обязал ДБР внести сведени...",
      "excerpt": "",
      "date": "11 серпня 2026",
      "dateTS": 1786448227.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/542",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "А знаєте чому таке послаблення? Й не буде впливу на готівковий ринок (не очікується).  Тому що за...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786389322.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/541",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "❗️НБУ в четыре раза увеличивает лимит на покупку валюты для украинцев - до 200 тысяч грн в месяц ...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786389103.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/540",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар 44.89 - 44.91  Зупинка на максимумах, завтра продовжуємо зростання. #міжбанк #usduah",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786373933.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/539",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Липень ще норм пройшов. Я рахував +0,7%. Вийшло краще. Серпень-вересень буде жорсткіше. Значно. Б...",
      "excerpt": "",
      "date": "10 серпня 2026",
      "dateTS": 1786373865.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/538",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Не почую - не повірю Але дуже сподіваюсь --- ❗️США ежемесячно будут выделять Украине ракеты-перех...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786186281.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/537",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ З початку літа 2026 НБУ залив у ринок $10,9 млрд валютних інтервенцій.   Всього за 2 мі...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786181529.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/536",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЩОДО РЕЗУЛЬТАТІВ 1ГО ТЕНДЕРУ 3х МІСЯЧНИХ ДЕПСЕРТИФІКАТІВ  Якщо коротко: ставка розміщення 3МДС ст...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786178285.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/535",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Якщо темпи виїзду першого піврічча в 2025 році будуть збережені, то по року можемо отримати найбі...",
      "excerpt": "",
      "date": "8 серпня 2026",
      "dateTS": 1786176574.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/534",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "як не згадати класику...  )))",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786110899.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/533",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Загадкові надходження до ЗВР, особливо по новій програмі USL.  Гроші заходять по USL? - так.  У З...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786110610.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/532",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Міжнародні резерви України 51,2 млрд дол НБУ",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786105879.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/531",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЧИСТИЙ ПОПИТ НАСЕЛЕННЯ НА ГОТІВКОВИЙ ЄВРО ВИПЕРЕДЖАЄ ПОПИТ НА ДОЛАР  За липень 2026 чиста купівля...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786105710.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/530",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Доречі, сьогодні, 7 серпня, перший тендер за тримісячними ДС.  Замість повного задоволення заявок...",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786101402.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/529",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Цікаво 🤪  Зазвичай мене просять долучитись до рейтингування, а тут сам попав в рейтинг )",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786098383.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/528",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "До попереднього посту #НБУ #інфляція #ВВП",
      "excerpt": "",
      "date": "7 серпня 2026",
      "dateTS": 1786098007.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/527",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ключевые итоги операции МоЛоЧКа в цифрах. Операция началась 10 июля 2026 года.   🔴Зерновой экспор...",
      "excerpt": "",
      "date": "6 серпня 2026",
      "dateTS": 1786031121.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/521",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "УКРАЇНСЬКИЙ ЕКСПОРТ У ЛИПНІ НА МІНІМУМАХ З ЛИСТОПАДА 2025  Митниця опублікувала свіжі дані по екс...",
      "excerpt": "",
      "date": "6 серпня 2026",
      "dateTS": 1786027133.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/519",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Є й позитивні новини 100 грн за дизель скасовується. Все ж таки, падіння світових цін нафти  впли...",
      "excerpt": "",
      "date": "6 серпня 2026",
      "dateTS": 1786000853.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/518",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Перелік брендів та бізнесів які зазнали втрат сьогодні через російський обстріл:  ▪️Новус ▪️Новая...",
      "excerpt": "",
      "date": "5 серпня 2026",
      "dateTS": 1785934422.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/517",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Продовжую рефлексувати, по мірі надходження інформації та подробиць про наслідки сьогоднішньої ат...",
      "excerpt": "",
      "date": "5 серпня 2026",
      "dateTS": 1785921485.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/516",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ДРОБИНА ЕСКАЛАЦІЇ  Я зазвичай не коментую обстріли. Хоча болить й тисне воно піздець (особливо ко...",
      "excerpt": "",
      "date": "5 серпня 2026",
      "dateTS": 1785919733.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/515",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПОПИТ ТА ПРОПОЗИЦІЯ ВАЛЮТИ У ЛИПНІ (ПОВНІ ДАНІ)  👉МІЖБАНК  - попит: 8,814 млрд дол (+0,6%) - друг...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785857478.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/514",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "МІНФІН ПРОВІВ ПЕРШЕ РОЗМІЩЕННЯ ПІСЛЯ ПІДВИЩЕННЯ НБУ СТАВКИ ДО 15,5%  1. Залучив 6,5 млрд грн (28 ...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785854619.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/513",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "BRENT ПАДАЄ НА 4,2% Це може послабити тиск на європейську переробку й стримати зростання цін в Ук...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785850384.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/512",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Продовжуючи тему ВВП за 2кв2026  Ось ВВП й деякі складові  ВВП +0,6% ——— 🔴Агро -0,7% 🟢Промисловіс...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785849075.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/511",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ  ВВП України в 2кв2026 зріс на 0,6%.  Це значить, що ВВП у першому півріччі 2026 показа...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785844059.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/510",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ШІ та безробіття (Marketwatch):  🟠ШІ вже додає +0.15% до загального безробіття в США - небагато, ...",
      "excerpt": "",
      "date": "4 серпня 2026",
      "dateTS": 1785838024.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/509",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПРОМИСЛОВІСТЬ УКРАЇНИ В 1П2026 СИМВОЛІЧНИЙ МІНУС  Ох так багато можно розповісти про цей мінус 0,...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785770144.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/506",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "МІНФІН ЗНИЖУЄ БОРГОВЕ ГРИВНЕВЕ НАВАНТАЖЕННЯ   Мінфін по гривневим ОДВП за 7міс2026: + залучив чер...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785754214.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/505",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар 44.89 - 44.92 Тягнемось потроху вгору #міжбанк #usduah",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785753467.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/504",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Рейтинг світових валют за липень 2026 - рубль серед ТОП 15 по рівню падіння до долару - рубль №2 ...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785748681.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/503",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПРИРІСТ ГРИВНЕВИХ ОВДП УКРАЇНЦІВ У ЛИПНІ БЛИЗЬКИЙ ДО РЕКОРДУ  Українці наростили в липні 2026 вкл...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785744279.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/501",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "УВАГА. НА СЕРПЕНЬ ВІЗМУ ПАУЗУ В ОГЛЯДАХ. АЛЕ ЯКЩО БУДЕ ЩОСЬ ВАЖЛИВЕ ТО БУДУ ТРИМАТИ ВАС В КУРСІ К...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785742986.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/500",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Якщо лінки читати, можете подивитись валютний огляд на каналі YouTube https://youtu.be/aKwW09CAGa...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785742921.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/499",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ ЛИПНЯ – БОКОВИК ДОЛАРУ ЗА РАХУНОК ЗНАЧНИХ ІНТЕРВЕНЦІЙ. СЕРПЕНЬ Р...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785742503.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/497",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЗА ЧИМ СЛІДКУЄМО В СЕРПНІ 2026: ·       1 серпня - підвищення тарифів Укрзалізниці на 30%. Пряме ...",
      "excerpt": "",
      "date": "3 серпня 2026",
      "dateTS": 1785742503.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/498",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ШІ портфель липень 2026 результати",
      "excerpt": "",
      "date": "1 серпня 2026",
      "dateTS": 1785569080.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/487",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ШІ ПОРТФЕЛЬ (результат липня, портфель на серпень)  Як й обіцяв в (https://t.me/shevchyshyn_trend...",
      "excerpt": "",
      "date": "1 серпня 2026",
      "dateTS": 1785569039.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/486",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "В липні 2026 року НБУ залив в ринок валютних інтервенцій на 4'793 млн дол (-5,8% м/м) для покритт...",
      "excerpt": "",
      "date": "1 серпня 2026",
      "dateTS": 1785564877.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/485",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Дякую партнерам за наше \"щасливе дитинство\" ))) Відлетіли від дна.  Завдяки зовнішнім надходження...",
      "excerpt": "",
      "date": "31 липня 2026",
      "dateTS": 1785508905.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/483",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТОРГІВЛЯ ТОВАРАМИ: ГЛИБОКИЙ ДЕФІЦИТ За 6міс2026 ⬆️Експорт товарів зріс на 4,6% до $19,79 млрд    ...",
      "excerpt": "",
      "date": "31 липня 2026",
      "dateTS": 1785505727.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/482",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ГРОШОВІ ПЕРЕКАЗИ В УКРАЇНУ  За 6міс2026 грошові перекази впали на 6,1% до 3,68 млрд дол. (проти п...",
      "excerpt": "",
      "date": "31 липня 2026",
      "dateTS": 1785503680.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/481",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРИ ДНЯ 😢 Украина потеряла около 50 000 солдат на поле боя. Еще 400 тыс. — раненые, огромное ко...",
      "excerpt": "",
      "date": "31 липня 2026",
      "dateTS": 1785485924.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/480",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "🚇📈 Укрзалізниця повідомила, коли тарифи на вантажні перевезення зростуть на 30%  Ці зміни передба...",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785423900.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/479",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ключові показники прогнозу НБУ  Публікації повного інфляційного звіту очікуються через тиждень - ...",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785418364.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/478",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЩОДО СТАВКИ НБУ ТА КУРСУ  Підвищення ставки було неочікуванним. Зараз ринок буде переварювати все...",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785417564.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/477",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Україна отримала 3.5 млрд євро по оборонному напрямку по Ukraine Support  Loan Мінфін",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785409909.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/476",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "🏦❗️НБУ підвищив облікову ставку до рівня 15,5% річних.   Підвищення ключової ставки відбулося впе...",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785409525.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/475",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк 44.61 - 44.67 Перед рішенням по ставці НБУ й макро прогнозами, які будуть через годину",
      "excerpt": "",
      "date": "30 липня 2026",
      "dateTS": 1785405895.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/474",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Середня брутто зарплата в червні в Україні зросла до 32 783грн (на руки  25 273 грн) Се...",
      "excerpt": "",
      "date": "29 липня 2026",
      "dateTS": 1785340368.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/473",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ще один на черзі (((  Полтавський ГЗК (Ferrexpo), може призупинити роботу через морську блокаду. ...",
      "excerpt": "",
      "date": "29 липня 2026",
      "dateTS": 1785335395.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/472",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Про порти в матеріалі УП",
      "excerpt": "",
      "date": "29 липня 2026",
      "dateTS": 1785331180.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/471",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ціни палива тимчасово стабілізувались. Найбільший приріст дизель +17% (повернувся на максимуми як...",
      "excerpt": "",
      "date": "29 липня 2026",
      "dateTS": 1785325748.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/470",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "НБУ продовжує тримає долар на міжбанку, заливаючи ринок інтервенціями та сжавши зуби. Тягне до рі...",
      "excerpt": "",
      "date": "29 липня 2026",
      "dateTS": 1785312888.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/469",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Південний ГЗК частково призупиняє видобуток через блокування портів й фактичну неможливість експо...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785258967.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/468",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "@&ять це плюс до 3% до кінцевої ціни єє для бізнесу",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785240817.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/466",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "⚡️📈 НКРЕКП ухвалила рішення підвищити з 1 серпня тарифи Укренерго на передачу електроенергії для ...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785240817.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/467",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "🔻 Після фактичної зупинки морського експорту закупівельні ціни на зернові та ріпак почали падати:...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785240276.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/465",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар 44,99 - 45,00  Такс... це вже заявка на перехід межі. Якщо до закриття не відкинуть...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785239609.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/464",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "У I півріччі 2026 року споживання металопрокату в Україні зросло на 5 %, хоча динаміка за квартал...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785239269.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/462",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Падіння перевезень жд транспортом за 1П2026: 🧱⚙️вантажів - -6,2% 👫 пасажирів - -15,7%  ...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785232876.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/461",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Міжбанк долар: 44.97 -  44.98  Вчора долар відігнали, сьогодні підібрались впритул.  Таки рівні б...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785231738.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/460",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Кругове фінансування ШІ та NVidia (Bloomberg) Nasdaq - падаємо на 26400",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785230325.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/458",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТЕХНОЛОГІЧНІ АКЦІЇ ПРОДОВЖУЮТЬ ПАДАТИ, ЗАТЯГУЮЧИ ЗА СОБОЮ ВЕСЬ СВІТ  Nasdaq 100 (NQ) на 27 930. Ц...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785230166.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/457",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Нафта Брент вже нижче за 84 бакса за бочку.  При цьому фьючі по ціні постійно знаходяться в беква...",
      "excerpt": "",
      "date": "28 липня 2026",
      "dateTS": 1785227264.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/456",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "SpaceX - найгірший після IPO результат -27%. Гірше ніж 90% компаній з капіталізацією більше 1млрд...",
      "excerpt": "",
      "date": "27 липня 2026",
      "dateTS": 1785166077.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/455",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "РОЗДРІБНА ТОРГІВЛЯ УКРАЇНИ - СЕЗОННЕ СПОВІЛЬНЕННЯ В ЧЕРВНІ 2026, Й НЕ ТІЛЬКИ",
      "excerpt": "",
      "date": "27 липня 2026",
      "dateTS": 1785161892.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/453",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "РОЗДРІБНА ТОРГІВЛЯ УКРАЇНИ - СЕЗОННЕ СПОВІЛЬНЕННЯ В ЧЕРВНІ 2026, Й НЕ ТІЛЬКИ.  Оборот роздрібної ...",
      "excerpt": "",
      "date": "27 липня 2026",
      "dateTS": 1785161628.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/452",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Ситуація з портами давить на гривню, хоча активного впливу на показники попиту -пропозиції ще нем...",
      "excerpt": "",
      "date": "27 липня 2026",
      "dateTS": 1785146657.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/451",
      "external": true,
      "featured": true
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Відеоогляд вже на каналі, якщо лінки читати https://youtu.be/tYvAcY3K6Mc",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990211.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/450",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 20–26 ЛИПНЯ 2026 ЗУПИНКА ПОРТІВ - ГОЛОВНИЙ НЕГАТИВ ДЛЯ ГР...",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990178.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/448",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "За чим слідкуємо на тижні 27-31 липня 2026 : ·       28 липня - візит Зеленського до США це найва...",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990178.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/449",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Поки НБУ тримає коридор. Фактичний влив портів буде в серпні-вересні.",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990117.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/447",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 20–26 ЛИПНЯ 2026 ЗУПИНКА ПОРТІВ - ГОЛОВНИЙ НЕГАТИВ ДЛЯ ГР...",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990085.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/446",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "На міжбанку й готівковому ринку дефіцит валюти знижувався",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784990041.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/444",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 20–26 ЛИПНЯ 2026 ЗУПИНКА ПОРТІВ - ГОЛОВНИЙ НЕГАТИВ ДЛЯ ГР...",
      "excerpt": "",
      "date": "25 липня 2026",
      "dateTS": 1784989982.0,
      "readTime": "3 хв",
      "url": "https://t.me/shevchyshyn_trends/443",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Китай вступає в економічне протистояння на боці рф?  Виглядає що так. Й це вже не просто так.   У...",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784900285.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/442",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦІНИ ВИРОБНИКІВ СПОВІЛЬНИЛИСЬ НАЙБІЛЬШИМИ ТЕМПАМИ ЗА 27МІСЯЦІВ  У червні зниження цін становило -...",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784898971.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/441",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "EURUSD нижче 1,135  Падіння відновлено й ціль 1,11 Повернення мит Трампа для ЄС, високі ціни нафт...",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784898145.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/439",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Це ж як її нагнули зі всім ЦБ... щоб ставку знизили",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784897144.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/438",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Путін продавив Елвіру в ЦБ рф. ЦБР знизили ставку на 0.25вп до 14%.  Незважаючи на прискорення ін...",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784890931.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/437",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "У 1П2026 банки завозили готівкові валюти лише 6 країн: 🥇Долар - 2,82 млрд дол (58,3%) 🥈Євро - 2,0...",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784886874.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/436",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "В Україну зайшли кошти МВФ 690 млн дол Мінфін",
      "excerpt": "",
      "date": "24 липня 2026",
      "dateTS": 1784883970.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/435",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЩОДО БЛОКУВАННЯ УКРАЇНСЬКИХ ПОРТІВ Я про це почав писати ще тиждень тому, в валютному огляді, фор...",
      "excerpt": "",
      "date": "23 липня 2026",
      "dateTS": 1784819620.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/434",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "БОГАТІ НАРОЩУЮТЬ ЗАЛИШКИ В БАНКАХ НАЙАКТИВНІШЕ  Згідно даним ФГВФО за 6м2026: - залишки коштів у ...",
      "excerpt": "",
      "date": "23 липня 2026",
      "dateTS": 1784817236.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/433",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Падіння індексу продукції рослинництва в Україні за 6міс2026 13,3% пер/пер. Важливо! Це...",
      "excerpt": "",
      "date": "23 липня 2026",
      "dateTS": 1784815638.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/432",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Брент вже майже 100  Ціни на стелях заправок продовжують зростати. Чи буде у нас 100? ні, якщо на...",
      "excerpt": "",
      "date": "23 липня 2026",
      "dateTS": 1784812062.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/431",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ПОПИТ НА ФІЗИЧНЕ ЗОЛОТО ВІД УКРАЇНЦІВ ВПАВ В ДВІЧІ, СРІБЛО РОЗПРОДАЛИ  🟠 ЗОЛОТО За 6міс2026 украї...",
      "excerpt": "",
      "date": "23 липня 2026",
      "dateTS": 1784799547.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/428",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЦИФРА ДНЯ Українські банки знизили завезення готівкової валюти у першому півріччі 2026 на 18%, до...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784736181.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/426",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "ЛАЙФХАК (промт Chat GPT)  Перетвори це селфі на професійний студійний бізнес-портрет преміумкласу...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784726617.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/425",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "❗️Крупнейший мировой оператор контейнерных перевозок Maersk приостанавливает работу в черноморски...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784723596.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/424",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Брент повернувся до коридору $90-$115 Зараз на $95+ Українські заправки - вже в тренді, а населен...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784714026.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/423",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Якщо ви пропустили НБУ планує посилити вимоги до аналізу платіжних операцій https://minfin.com.ua...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784713527.0,
      "readTime": "2 хв",
      "url": "https://t.me/shevchyshyn_trends/422",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Замість тисячі слів про перспективи України.   Спочатку Ковід, потім війна. Й війна продовжується...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784707402.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/421",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "Я вчора це написав по мотивам заяви російських ЗМІ  Російські маніпуляції.  Виходить в російських...",
      "excerpt": "",
      "date": "22 липня 2026",
      "dateTS": 1784704823.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/420",
      "external": true,
      "featured": false
    },
    {
      "source": "telegram",
      "tag": "telegram",
      "tagLabel": "Telegram",
      "title": "10 річні бонди рф - майже історичний максимум  - 16,86% (якщо прибрати виброс у лютому 2022, й де...",
      "excerpt": "",
      "date": "21 липня 2026",
      "dateTS": 1784650641.0,
      "readTime": "1 хв",
      "url": "https://t.me/shevchyshyn_trends/419",
      "external": true,
      "featured": false
    }
  ],
  "news": [
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "РБК-Україна",
      "title": "Курс долара 2020: які зміни чекають українців на наступному тижні - РБК-Україна",
      "excerpt": "Згадка у виданні РБК-Україна",
      "date": "8 серпня 2026",
      "dateTS": 1786173845.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQeGpvaDB4Z2dncDh6RzhLNE85cmthOGNkQWp2LVE1M3NXS3RIZ1BMczgzQlc2cjVCdlRzX1lGczE1ak1GOGN2NGFCVFBBSk5PcnVqSGd1NEwyQUxCRFUybXJncWhjc2N1UTBfWjZXcjBSRXVyVmN6OTh5RFhzZlg0YTh4XzRjeWRVT0ZTdGRSNTBEQl9FSmYtS2NnSHHSAZwBQVVfeXFMUHhqb2gweGdnZ3A4ekc4SzRPOXJrYThjZEFqdi1RNTNzV0t0SGdQTHM4M0JXNnI1QnZUc19ZRnMxNWpNRjhjdjRhQlRQQUpOT3J1akhndTRMMkFMQkRVMm1yZ3FoY3NjdVEwX1o2V3IwUkV1clZjejk4eURYc2ZYNGE4eF80Y3lkVU9GU3RkUjUwREJfRUpmLUtjZ0hx?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Радіо ТРЕК",
      "title": "Долар може різко подорожчати вже у серпні: фінансовий аналітик назвав можливий курс - Радіо ТРЕК",
      "excerpt": "Згадка у виданні Радіо ТРЕК",
      "date": "3 серпня 2026",
      "dateTS": 1785763200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxObUduTll4TlFjQjlWQ3Zvdk1vLXhTV3RMbThFNWlTRVoyWm51eEZyaU5BS1NRLWFOY3VlYTAydmhmYnFOYXZKWFdNWHphZzdwaV9UM0EzMDl0c3diMFlWQmFQbGtuOWRsdU1tR0FtQmEtQk43UE5EM1AxWHVFV0hEdlJwME1ZTVBNdTNpckY1VXNjQ0FMTXRWX0N5R1M1dWdOVGY2bDNGMS1hZFMtSHlYRE8zM3VVWDlPakdEZU9kUWIzRmpfSjcw0gHGAUFVX3lxTE84dlZnRHFfYzBSRVZoR3BaWllxSVhsTGF0eEdSXzdYdjk4RGVscGZnSHBfWVl3OHQzOTI0MGFpTkhsb1E4WHN5eDZQZU5FOFBVMlZtNEt0TVY5TjJ2ZHBWSWRqUGdBZ1V0X2FaMFBBUm1wZVo5U2pSXy11ekxRb2ZSQThHcndqZ0tsbnZramw3bmFTdk5RMmF6dXRSTl9ZQUZTOW4xbzRxUXFFU0w2eGdvMVgtQ0V5bXNlZDBYdmMxWXdqVjlkdw?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "УНІАН",
      "title": "До 46 гривень за долар: аналітик пояснив, чому гривня ризикує ослабнути вже у серпні - УНІАН",
      "excerpt": "Згадка у виданні УНІАН",
      "date": "3 серпня 2026",
      "dateTS": 1785749400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxOME5qelBEdFVlWU1CU3RJV2hpXzZHOGtaaE1FMzlPMzBaczlQaGxSeVMxWEVyRWV6MEliWDNFclQtblMtVy1KRGhrejBxanFqNjBkc2xjWkI5dDIzQmxsYUF4UkpkekN4c2NkSkV6VEZWblFBUWpnWWV1OHYtcGxUYXYzbFZVeDRfZi1tR1NJWVd0M3dabU93U1RJTlV0RXlGaFdiUnIyVnVYQVZ3SWFLSG5BT0w3ZW9iOXBJMkZ4R1QzYVFOTk1qQU9GWHpZYnJjYTc5YWIxZEMxWWltanBzd0RvUHFKQlVrb091WUEwb1FFYlphRWZSeGN30gH6AUFVX3lxTE4wTmp6UER0VWVZTUJTdElXaGlfNkc4a1poTUUzOU8zMFpzOVBobFJ5UzFYRXJFZXowSWJYM0VyVC1uUy1XLUpEaGt6MHFqcWo2MGRzbGNaQjl0MjNCbGxhQXhSSmR6Q3hzY2RKRXpURlZuUUFRamdZZXU4di1wbFRhdjNsVlV4NF9mLW1HU0lZV3Qzd1ptT3dTVElOVXRFeUZoV2JScjJWdVhBVndJYUtIbkFPTDdlb2I5cEkyRnhHVDNhUU5OTWpBT0ZYellicmNhNzlhYjFkQzFZaW1qcHN3RG9QcUpCVWtvT3VZQTBvUUViWmFFZlJ4Y3c?oc=5",
      "external": true,
      "featured": true
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Vesti Ua",
      "title": "Курс долара у серпні: економісти пояснили, до чого готуватися - Vesti Ua",
      "excerpt": "Згадка у виданні Vesti Ua",
      "date": "3 серпня 2026",
      "dateTS": 1785741000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPTTU0OHBTUEtQRWxGWThsTUlZejVCZnp4aHBmUFlaeW5qQWpaRE91YlliOGRVQlc2S2xEU0I2dVh1akdzcjVyNW84aVc2eUNqR1NsWXdQYnR1YUsySkI0SmVGaXJZTFlJZk45SG1UTTN3RG5yRFdweVRRa09GTDZHd3E1QnB3czVCQkM5ODRqS1Jxd08td2xLTlp5SEd0VVpNRzNYdVJlUjY3ckxFU0tydA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Врожай під загрозою: в Україні різко підскочать ціни на один базовий овоч - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "3 серпня 2026",
      "dateTS": 1785740400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNcEg5T3kyTU1kcGdmNWVOcU5aZ3lmS3hwRHBtODQ3QXRVTkEwRnhxNHMydWpKaHEzN0ZtbXVlamY4SnQwdlI4Z21lLXEyOHlRNG5oMDJnTW52VjR0SU83d040MnNjWkZxeU43R2ZJY0d1cE5CV3o5UlVJZ1hsUkhzN19wU01wMlVEVjJSRG12bElxUVpfR1lmVHZSU0lRclQyN0dqTnFOYi11WjdqM1pPdG45OXREQWtw0gG-AUFVX3lxTFAwY3RsQTZjVkNLdm9ReVZ2a2tIcjZnb1h6eU8ySG8xUzQ0bDZJUW1SblZGdG9rTlMya0lhLVREMGdQblBJeGpyUmZMR245ZkRBMVJIVHMzS3ZHOWRCaVN0QlBueXBoLXhhSFU0alVFd1owRjFIRUZ6Y2NGc0dPZEtYMTdOdUZxM2ExYno4cVAxS2J5dVpBLWVnRlR3TE1uaWwyTW9VWHlSZmZPQ3gwQnRjWmhUbnBMOFpjd1BuQUE?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар готується до нового стрибка: експерт назвав терміни та можливий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "2 серпня 2026",
      "dateTS": 1785694880.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOc1NmMWZzQ0VXVVRWR0NHdVVNdFBvSy1ISnZNRG5DYm1RUG5POTJCSGVTR2RSNkJKaWt3QmRudHhBR2tfRDhsc3otN05hSFpvTjNXV0lobExSWkZqMzUwRmxSb1F4QTZ1TXlhY1BYZEZQaHNuei15ODlabDR1SmZrT21pTjRtek1OT1BkUkRLdUhWeS1JeTZGeXE2eG53SFlWZE5tQTh0ekg2bUJaV2lBa21QVDJmWnZY0gG-AUFVX3lxTE44TkxvUzVzQzdQVTc4S3pwb3BQREJpSG42RGRmTWFpbVhFYUdVOTB1RmMzeWlnNWljN185UElMVGptMHZvZm5QdDFaQXVnVFQzSHI2anF2NUk1ZTd3b1BoZF9zOXRIbC1lV0RxV1FIbENGTEVQRkxzUVRsLV9kOWhselBaLUdERXVjNEdlMmV2dXlIZmxZNkJEZFhMcGpjd3UzTzBIZmhORXpKSjgtZkg0cUYzc1ZfT0ctSVBWZ1E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Долар готується до нового стрибка: експерт назвав терміни та можливий курс - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "2 серпня 2026",
      "dateTS": 1785694880.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxOOE5Mb1M1c0M3UFU3OEt6cG9wUERCaUhuNkRkZk1haW1YRWFHVTkwdUZjM3lpZzVpYzdfOVBJTFRqbTB2b2ZuUHQxWkF1Z1RUM0hyNmpxdjVJNWU3d29QaGRfczl0SGwtZVdEcVdRSGxDRkxFUEZMc1FUbC1fZDlobHpQWi1HREV1YzRHZTJldnV5SGZsWTZCRGRYTHBqY3d1M08wSGZoTkV6Sko4LWZINHFGM3NWX09HLUlQVmdR0gG-AUFVX3lxTE44TkxvUzVzQzdQVTc4S3pwb3BQREJpSG42RGRmTWFpbVhFYUdVOTB1RmMzeWlnNWljN185UElMVGptMHZvZm5QdDFaQXVnVFQzSHI2anF2NUk1ZTd3b1BoZF9zOXRIbC1lV0RxV1FIbENGTEVQRkxzUVRsLV9kOWhselBaLUdERXVjNEdlMmV2dXlIZmxZNkJEZFhMcGpjd3UzTzBIZmhORXpKSjgtZkg0cUYzc1ZfT0ctSVBWZ1E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Економіст попередив про новий стрибок долара: за яких умов курс перевищить 46 гривень - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "2 серпня 2026",
      "dateTS": 1785675600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxNc0pkUW1ueWZKeHY5RDJaX2ZaOThUcWtEZmUwc1JvZkJjUG1zZVpEWUlHdjMxS2JBb1VPRGxSUzcxSkZ2dU8zbzBPTk82Y2E3UmUwRXhDRHlBY2ZfcE5QdHFLVnM1UVZRTTB1a1hqRzBnRkRzZmhtVXlYaUVIQW5DWHEzME5vZDVrel80eEF2OXpqcF81VWNhSkJBU1o3d1lOSUN1bEJkdnIxMkt1S1JNOEQ5RG5xb3oxTHRpaEt4ZGFMbUHSAcgBQVVfeXFMUFR1UzJ5TVVfdDZnc2pWTlFXVUZBbVA4cDZLa3d0N3ExV0xJS3RWOFN6dDU4VTk0eUUyM1hTeWtoYVpHd3hocEhpTEdIb3NYa2UxYlR3NWJmZjYzR3pydjNUa3hxSFBXcFV2NFk3V2JCVTBqRndTVFp6S1NqUlVBaUM4X253VHViaXRIS0hEYnl0WTVKWWgyenQ3akd5UnRqWGUzbkZjNktDc0cwUEJiNURxU0JxNkJxZjZWTDhzc0t5cS1QOVprc2E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "cryptos.tv",
      "title": "Економіст попередив про новий стрибок долара: за яких умов курс перевищить 46 гривень - cryptos.tv",
      "excerpt": "Згадка у виданні cryptos.tv",
      "date": "2 серпня 2026",
      "dateTS": 1785665400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE1ab3pjMTdzWGxNRnZsamZCdDl0MGNFT05nc0JRQXh2YnJUSTQzaG1aMm4zLVYwUDJZaDBHYzZFUVU3dEVKR2F1UTBlS3h5SjJuR0gwY19ISnVITlRQWG9IUDR4ZVNUWkVLek50TDZPa2FvTGo1UFRseEpGaEo4eVE?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "В Україні очікують новий стрибок цін: економіст назвав головні причини інфляції у серпні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "2 серпня 2026",
      "dateTS": 1785654000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxPOUZYNVVGaHdWNUtQN0VRRWRlblNUU1ZXTEVsbVhXcEdKcUVqUXZrTUxnXzZQZnlvbDZrTlZ5VTE2dHhBQWE0bnQ4TXlnY0hPUEtrQWtqUXEtWnBxbTNpUVNNZTBMdVRjNGdOSnVwYW1VaHhvTEJJNUlFWE9tWU9PRG5KNUlnWUZ6cUtTSzZLdmh0NVY1Y0NVcktOSVVwUHhDeVpYcDJKb3BkWDRwTFM2djIxWTFNdFhmYlZNRVJrVTRwYVhzZjBhbXZnVznSAdIBQVVfeXFMTUhMR01GTzMxSFVtRnU1elB0V3JWaV9qOGRzWlRDVE5vampFVVRXcWx3NFBza0F3MzlXSHg0X09pdkNKd21QQ3R5OEI2ZHlBQmZKRnFYOTZQenJOelczUnRzUDdFeXN3TWVhOHFXVGZaM053VldEYzVVQ1psbzdUUmpMck84TkF2TElCRTdjaVhBWHphd3RwOEZra0ZVSTcyb1FWdzVFN1lHc1JISGhsN013bW1iVnVud3YtbUc3QlpHVlpPc18xTDdiTzB6V1NvRDFB?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Водіїв попередили про новий стрибок цін на пальне: названо терміни - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "1 серпня 2026",
      "dateTS": 1785609763.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxOS0doR2k0Y1dxMUpaTHpXbXVySzcwTkpwRVdjTXJvWmdlbDhOUjg0N1NQMFg5NVlWeE9qcW91UFgwNFhGaDh4dkVxWlpoY0NXamg3a1NEU0dxTVNsUnY4ZGhhZTFpdDc5cDF2Z3pkQTFKcG0zRmpWTms3VGRlc2ZXV2xkaVgzS1Z3YmZFdXZRSkVsMGd6eU1jV1JqYm1xeHY1c0pmTGxVMXBXQlo4ZV9B0gGvAUFVX3lxTE5LR2hHaTRjV3ExSlpMeldtdXJLNzBOSnBFV2NNcm9aZ2VsOE5SODQ3U1AwWDk1WVZ4T2pxb3VQWDA0WEZoOHh2RXFaWmhjQ1dqaDdrU0RTR3FNU2xSdjhkaGFlMWl0NzlwMXZnemRBMUpwbTNGalZOazdUZGVzZldXbGRpWDNLVndiZkV1dlFKRWwwZ3p5TWNXUmpibXF4djVzSmZMbFUxcFdCWjhlX0E?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Водіїв попередили про новий стрибок цін на пальне: названо точні терміни - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "1 серпня 2026",
      "dateTS": 1785609720.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNaEEwU1FXdEd4VDhlUmRQME5TaFRjWGFBcmRBa1E0MUF4RTFncjZDUDVCNlJBSWRCNVUxeUZndnM3MHdDaWJKTURZNl93c28xNm42LWc1MkZ1WjNEMjFNZFJLWGQzOU9nSzFxSmllck5tLVdUY2tyTEQwaVJJbUFsYVdoa2lGVi1IbXRmZVBmYU5DWDUxbVlfU1lYMzIzWDQ2MmdRRk9TQW5mUdIBrwFBVV95cUxOS0doR2k0Y1dxMUpaTHpXbXVySzcwTkpwRVdjTXJvWmdlbDhOUjg0N1NQMFg5NVlWeE9qcW91UFgwNFhGaDh4dkVxWlpoY0NXamg3a1NEU0dxTVNsUnY4ZGhhZTFpdDc5cDF2Z3pkQTFKcG0zRmpWTms3VGRlc2ZXV2xkaVgzS1Z3YmZFdXZRSkVsMGd6eU1jV1JqYm1xeHY1c0pmTGxVMXBXQlo4ZV9B?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Новини.Live",
      "title": "Найближчими днями ціни на дизель можуть сягнути 100 грн за літр: експерт назвав причину - Новини.Live",
      "excerpt": "Згадка у виданні Новини.Live",
      "date": "1 серпня 2026",
      "dateTS": 1785604020.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxOS2JhOE05M3pjYU5WejkxelRiMW1lZGJhNS1RNEFMOGEzRjJfRUs4MDNUTGpKYjA2UkpHTlVHS1d0MDcyOWNwdk0xOENKalFzWHdtVS1sTnF5UlB0b1Y5X2xETUF6NXpCY19Ya1M1M3J5QjJzYnkySUFydlBOMC0ybWZ6TXF5dFoxYmxSVlg1YWRkWWFGN1hOZHNtN0YxS0ZFYUZ2YU5pSVVFdWxGd0FsSnFpNmV3cTNfM1hnNlI4eVotX29jdUpz0gHMAUFVX3lxTE02UWsybEJSMW0yWG1pMHdWbThOa3hQdGxrU3pzS2pUb3JoTTVUT0liZnZQVDZfZlIyQmRGZkRhVGZ6cHQzSWl5eGJkVDFfOHlGOWxzRjRzbVhBaTNsTGllek5WdUR1NUw4VEZ0YUhVU1lmQWNDR2Y1ZERKWFp4UlJGb0N5OUF1bUpDMURqX0JxLTVGNUZpMkdCZ3RUSjAtcEx1eVJKWl9YTXpnTmFSaVBDdlJmRDFNNXdsaDNYY0R4RnR1N2ZHOXFMRjU4WA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Долар може зрости до 46 гривень: економісти пояснили, що буде з курсом у серпні - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "1 серпня 2026",
      "dateTS": 1785567971.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxQRmdiUHdtalcxdUVUOGkwLUVNV1V2RWVuZV90Ukh5U25qYUFvM3RvNW94Sl80SEtKamdvdmRvRW81RHlnU0UwN2tVRXprR1JKemt6YnUzUGNheVZWT3lxMnFqWjVDb2djelBxM01HbGt6UXRyTWJSMDdLbzhDOHpnM0lOQzVqYWlzWWRkRHFWa0R5eFBFRllQVWJkZnF1clZWR1FuUWVVWC1WQ0lqUm5rQV9QdmRGa05jV3FzalRWbUFmTl82SXpJYXB5aG9vUXVjV1o4emVKLXQxaHRzVnJQc1Q0NENoZHJSWHROUEZJMmlfbDg3NkHSAfcBQVVfeXFMT01rSjFyQkdKUkhCaUJGNDU4TW82aGo2VS1KMEtCMmNZTEE2cnlWWjFZU191UFNYSF9UaHcybDE2Tjlkd0hmODh5RzVTRU5LLVM4TmlfaWdCTHBlUGhEcFdoTUgyX2hncnJ5R25VcnBRaWhYZTVlVThzM0RBTzhEYmNpZFotbWpOcnFIT2tYcERURk5wOHdmRng2RFhuRDE2MjdfVm1vMU1PdFNINFlQeDZuZlNjNDk5SDhZWUxnSlpuZS1vV1ItSnZYWW9MS2F5M0RobzExSkNxc291UWN3UDVCMEoxYnUtUmFHU2dTeUtrdGhEQkhTNA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Радіо ТРЕК",
      "title": "Долар може сягнути 46 гривень: економісти озвучили прогноз на серпень - Радіо ТРЕК",
      "excerpt": "Згадка у виданні Радіо ТРЕК",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNbzRVR1ROTEhyR0R5SXFWcmt5MkxQdGJpWUE4eWMteDUzNkJMSVNWQzktaGpXaHc5QmZoLXpHcUgwRnp1Q2o2elBqYUxtWVV0N1NZTWVqOWdva2QzM1c5d2JCQXFaTk5weWtidWt4LTZJRDdzZHBnZy1YN0hoOTRjTmQzTHI4R0FycDVSWEpVVU5IcnRNTWptNzBNMXF3TnFOb0V5RmNzcllUWUVVbjUw0gGuAUFVX3lxTE5FYmh5TEZVVFA0NnlXWkl5dHB1SVZVVGx1Z2JWSFZiUjhvWFpBR3lfc0l6N2hBZlJkd1ZVSFJ3MFJJMlpOZTI2RThfbUduUXRuUER6T3FabmQ4UWhla3Raa1J2NVFDbGNRcm9DeHBkQS1YWjFhcVZuTUFXelNoSHBEUGRUaVZwVmxNc2I3TVBIaDA2cS1GZDJnZTEzYy1zWjlUaklLRWduRW94bG9PQQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Долар може зрости до 46 гривень: економісти пояснили, що буде з курсом у серпні - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "1 серпня 2026",
      "dateTS": 1785567600.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxPb1dYejlrOUpYaDdnMjZCSWJ0b2Q0UFRJeXhiSXFWbXJBY0hQbFJpaDUyTThGMlJJWFd0QU9rdzBfTWpZeDVYOW5Xbk5UbXZWOElUUXFndzJ6cS1acExoaUpFTVdiNEJ5Znl6U1RLNF9tQ2YwQ3Nfb3F5c0tTU1A3TXpHbVNFcmI3WjZHX1FkVnFVRFA3TUktcWhsRi1EbTVMenl2QUZsN2dDZGpEQ3pHelc0bG1SSTB6cUHSAb8BQVVfeXFMUDBXSkdkWkxncE96c25vdmtMTnlEN3JBRmNLNnZUY1ZnVmxDbzhIZ01UamVfME5yaGtaaF9GWWN5dFNtT2poVnBtQzloLVl5UUJCTU5DZ2loUng5dUZBcUwwNnRNS1VwdEhWcDBUWUE5NnhuSldhUmxydDB3Z2tDcHA4alQ1ckk3d2ZDRlhSVm1yeUZYTnczY2FGaXM3RVN2SUg5eDhac090ZWRVd3hZb016TXkxTUFDa2NJVnV0LUk?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Катастрофа з бензином, дорогий долар і висока інфляція: експерти ошелешили екопрогнозом на серпень 2026 - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "31 липня 2026",
      "dateTS": 1785481200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxPLTB0N0pWZVNsQWh0aVNWa1FqRXFBSHlWbkVScVVMLWx4d2p2NWhSUExwS2xjc0tSbXRTYk55YUJlZkdIT1VMQmV3X3gzcE1FalplbmVkalBMZzRIOGl1R18tYW8xNHVnMnEya1R4ZE5RM3hvVnFqV3NLN1hKS1Bmbno2MG1Db3ZwWkVrNDRLWjNwYlhrOThCV2JONTExSFBhMERkdlVwQXZUVjFRTExrTnZGVzJRdDQ0RDIzM3IwZWl4dmFZdjJieUdpTdIB0AFBVV95cUxQbUUzaGx5WHMzWmNTcXYyQVhOWGpMVjNpaUkxTlBkdG1uWldoQzhOMjF3TXRnVnRUdWV3a21xMFNHUDRNam9mY3RFRXJVcHFDeVdyaVd0Q2RnN0lyV1BsWVhuX3ZubzVST3YxbWxESGpfbDdSMUlodktlamxaaDJ2Q1JWZ2J1MDU4NnFPemVYT0l6dnFzalY1dmdDdlVja2VTNWJxZllZcjBNaTVUOURpVTQ3YUt0ZEZrdXBUUnhkajcwQVdhamRqbHBHNkdtdURI?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Блокування українських портів: що буде з гривнею, паливом і цінами - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "24 липня 2026",
      "dateTS": 1784876400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxQUGVGcGdpZVBMUGkzV05DUG1hNHhGamMxclpFaTlKUHZxcXE1SVhnSTA4aldCYUtzYzlxckJiQ0FKNV9tWDZZNnV3VlpxTzJWZnNDbk5zR3dtNktKUUdtdnY2eEVJa3dNZG4zazNLRVZCcWhkQ051UGUxUUFGR0lvUk0yRXVKTG1jLUE3STNXUm5sVm05RGQ4SW8zOGZ5b3ZFaEI4MzBXUlQyX1lUcDFzUU9ZZmJXWjB3TTlQNNIBwgFBVV95cUxORVJ1YTFRUV9aeTdrRmd6NUItT1J4SDVTcksyZVcyVDZQOThDY0o2YlBoaERJUXJJc2hXalFPZG1iT0s3OHROdUF3SEtnYkE4dk55NFYwYzFOQjdwSFJxdlZNLS1CaDlLdlYxNy12bFBXUFBuMVpuQzlfb2dWSE1FRENIVGtSMnVVMlpkazVkUFprdDlqU3R1OHZVN2hpdFdBQ3NHeG1aRXJvYlRuMW9kUlpHRGpaTWZtc0pvZkdJeHBQZw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "Главред",
      "title": "Ціни на товари та продукти підскочать: розкрито, що подорожчає в першу чергу - Главред",
      "excerpt": "Згадка у виданні Главред",
      "date": "23 липня 2026",
      "dateTS": 1784829216.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxQaGNxalgtT2ZpRVpNTi1ZVmcybm05ei1CSHY1azBDbGlFQnpPUGEzMzZpRXVURHR2c1FDcnVEZUE1dHlwc1NHVUoxdGY4bFZkZWRpaHRNRVI3TUlUdmJuczJCWnlPYUllLUVhMEVfcS1Ma2hmN2xSQmM3RFJtYUZFaDloRjVZV1U2UE5KX09kYzVOUFNzLVJaS0QzYnJySjc0YmdOZXVQMjRhb3R3NE5BdXFFbUdTX0g1OUlVaTFmVXpTQdIBxwFBVV95cUxQLXdJRm5xRElGSkY1dzc1X0hIR0JLLUJPODVnLUkxTnBudDc0M3p6RV9meVU3WEd2UDdrTzFYaUpZUGhtOUdhM0R0d2hpMFBPN3hUbnd1MmNTWGlfcVJEaVpxMWc3eWl5b1VnMmRMc3VSYl9VM051V0ZBTC1mSUQ5S0paZ25pWF9Wekd0elFiUEhCWGZIMV8tNlVSWWhHeDNQa09WNjU0RjU4Ynk2NEVQcDdDVkEyMFY5OUdDTGxtRjdiSTZGcDJF?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "УНІАН",
      "title": "Зростання долара та подорожчання низки товарів: аналітик про наслідки закриття портів - УНІАН",
      "excerpt": "Згадка у виданні УНІАН",
      "date": "23 липня 2026",
      "dateTS": 1784820480.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPb0VHcWs2OUc4bHJjTTJNSkhNVWFld0toNUJRUHp4ZkdpbmJBak9ZVlY2bGgwcl9ZaWlCLTNGeE5TMnZnV2hiRklWVHVjRTBUVm5qZl9STGxSeEtESkJLaFJFUW1WUERZMDEyQjV3MXY5RldyRVRETl9rd19SNlpxOXMtWDE3cVE2TkVPbjNlWGh1V3ktWHVkQnh4QnJsWHFaM2swek4xTUI5Y3RITUFna2t0RWstZ9IB0AFBVV95cUxQRGJnWWxDQVhNbkFYaGdpY29Bam9VcW9vTnNEYXBjMTRIbFZ3VDcwRnN6NmMtdzQwZWVHZkhrNlV6VVlHNWIxdzBiSlllS1hTVm9VTXRRdllXZ2oxR3MzWmNRTmZlRDFuclhEWG16eHhfMmdQTzdid01vTmhFRC1LZzJQdUN5ZW1XdXJoNlVzR3hNQXA5WGtxaWpqQm95c0xYRS05MTFYNXBGdWtiM1dyZlUtN3lxZWpVZnJDRUFoMzY5RGE2am01aUszOW1mY3Nn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Українці відмовляються від долара: економіст дав пораду, яку валюту краще купувати, а яку — продавати - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "20 липня 2026",
      "dateTS": 1784542739.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxQM3lieGx2ci04QXl6VzVaSEtaTVdBb0NVOWRKcE9ScDdyZmh4VkstQmY0dlJWVDEtVkU5Ty1tM0lldkctV0RuUzBIMl9VSkdlYjlNY2hMVnJEZGh4aXptLUR4Mm5Md05hS25pdXhWTXZqeFFLbmgyQV9ueXVpcTZES1hwWmZKbWptUFlMY0t0cU5ScWhjc0ctNDIwWktmZzhwY1M0OFlEN0tpOG5mQXV2N2R1Z1RQaU1MZzZfUThYWk1vdGp6VHBRZTBlbm5rSm1vcWdYQkJLMTdtWHFC0gHiAUFVX3lxTE9ac0hYb2NfUW0xS0VrVW1ZTllUQU9mbDkwcV9oaDRKcFBNb0UyUXFYTUZIN0V5ZkhVS21VUU9zUUhfUTRRNWZhRXAzU2oxcVFURnZPLXdFaE5lOUVPUEk2c01vcklpS0xjRzJhLVBUdExGU1NVeFFDTVJxVkRGdFhYZnhMcVl6VHRIYTNSTWFzcVpoeXFINDluS3V2Vlp4MlFBMkQ3NEhDVWp6QzRIUFQwV0p3ZklOam5wU0lmaUl4M0xBTDdKU3hxR0ItNzJ5UEdkZDYxTTgwRUR6Slk5OV9tUXc?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Курс долара готує несподіванки: економісти ошелешили, що чекає на гривню найближчим часом - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "17 липня 2026",
      "dateTS": 1784257572.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMikAJBVV95cUxOUmNoWDNva2Rvdnl6X3BGbFFXWFNaR3lpZVpxZm51Z19CdkpSaklFUl94bVVwdEtmUUthd2ZCZ1A1c2hzMXBjVFF5MlJpVzZWd0pwekFWU0J2VzFNQUVIYlNFY1h2RlBMZTI4WEhENjBJdHgwOExEWWVrV25UdkZ5VjZNY193NnB5WW9CVVBTcGVoRm1tZlJ5OGF4bkFjWU5KSktXeE40SzYtbEd0WlJHQXZzdW9CcGhWalFoeURROUFtSEozZUR0R1FuOFVTWjNUcy1ITGo2SE93a0Q4NE40SzFGMUFodERsTWdoM0JmNjZkbGU1djBycUh1dllEd2tKNS01UGRQTXpySHBwQU1DWtIBkgJBVV95cUxPYkdCNVIxbUVfTWdvRlhJdWNzY2NJQXBLUDAtYklfZ2RmUXpfQWJlMVk4VUpfNEg3Tm1NWG5sb0F4aDRlYU1IUHZRajVwbnpIVklJeHVZVEJhSi10SXJnbUV2cTNScW9fU09RTURIMWNrUWU1SXNoMXg0dVNGT1ZWZ1hmR1dlMU5fTTE2RlViZ1lycl9FeG1oQlBtWk5ZN0tUUWxvS2lnVXVPMjRjZ1hfUzQ1eXV2ODBEX2xYdEtlMVU2RENZdjVBVTBNS0R2ZWFFMjU5RkNzN1BSWkpDV3hCX0xlOF85aXdIQ0s0bW5uczlablZiZ3d3UzV6RlR1bjRQRjFkejVtZUc0b1p6SDM1NXVn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "ТСН",
      "title": "Курс валют в Україні: реванш долара та \"пастка\" для покупців євро - ТСН",
      "excerpt": "Згадка у виданні ТСН",
      "date": "16 липня 2026",
      "dateTS": 1784185200.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQc3BvVmZHd18xYVZlVllkR21mSWxwczZpWjVwYXlpNTNnVDJudWdDWDBnR1puODNGaVEwQWpjYTd1Y1JGX2ZUdi1SRmVvWk9naUJNNnl4dmRrb0FOWmFadTVoaVhVbUJxTjkxdDhoQjd6OF9vSVgzbFdKVUluTXFnYmxUd0NvRFloOTNMV3hTcFl0NW1DbGN6V0QtVm1RYTBwNF91X2dPQnRVd9IBrwFBVV95cUxOUXVaSlRvSDgxZklXN0ljM3BiNExUeFk1dlBkREJWZ204MTJkSnJmLUJTcnZfVTVaMUhCUUxNSFhzOG9qQ1IxX0tIRXkxejBWeFdZUloyRW1jQVZidS1VSFlRYWd2MWFnS1BwblVfLUNwZ192c25LYzNHbEYzc3BEZkl3Z09wQkRSQkx0VHBYRzBsNllmQ2kzd2NYSUNjaGVuTXhEcU9ZSTc1dDVTb2NB?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Які наслідки для українців матиме підвищення тарифів на проїзд у Києві — експерт попередив - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "14 липня 2026",
      "dateTS": 1784050572.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxQWUhneEQ2Y2d4ZExqeTZiWndhbGk0YUhNWF9uQ2prdjZVM2tMeEtueFNrZGNvQm9rYUpJNkgzQVpNR2lMZTI1MGJtY2ZqVHBLTTJrR1VLeHNzcDhYRWN6MndiZGZpeldnak5yZkdxOTN4VHlqSE9RUDRVanhiWXZSYnlfLW5BMmVnX2VXN2k2RGZFdC1NVmdaNTMtb1B6VGExWUhkZFpNc1VHenl4UUFTMmRzendBdllVU2lXdkttTEhDdEJMUDJvQm15ZTVncEtHdHM1emJlUk5fRm_SAY4CQVVfeXFMTW1XT0FvWDlFYmxKRUUzMkI4LWFoS3pQZFVRSEFlMEd6cDJ2LWhiaFlkNjZDZE9RYzBabEo2Wk5hZGFUb1N4M2ZYdXhJdy1vNmFfZjc4MkpELThaNk9USHVXZmdsRnhOSVgzM3NwQmV6ZWE4NGNNVC15TlBxb3JEMFpFM2VuUXc2U29BczY3dU8xNlRXUHRCT3VYdTZYanNYeFhPVWZDelJYdmNsbEJ2cWo3WG1sRm0zT2hPYnZnb0hsRDFQb0JKSzVPeXBpWVZDcjZ0cUpzRkk1Mll6bmdXREZ0SGZzbWZlbWNrT190V2M1VUYydFR6WlJvWEtqdDBOMEhmbmtuU1BwSDdCaFNn?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "unian.ua",
      "title": "Усе стане дорожчим: аналітик попередив про неочевидні наслідки підняття цін на проїзд у Києві - unian.ua",
      "excerpt": "Згадка у виданні unian.ua",
      "date": "14 липня 2026",
      "dateTS": 1784012400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQNHZ6SkExSXBxaEZ2ckZuOXU5alJvMkZtdU1xNFRhTU5lcGRUd3lHQTJOMkFuZXZkRWlfaUxsUThLVUpCekZOYmNsbHd3dVlvT0pEOUFGR3JidFpTMEJWQlpuYTlKb3R0c2ltbFhjS1FIYnI3Z3BONXJJaFIwcHR3Y3pXaUN2enNKWlVUa2Q0X0hLa1JISFg0VjBBRHVuanUwZ1hwRmc5SmxHZ2VRcktOM3hvcmMzMHhNNE9DZmNIWWFVRTQ5TG1oYjBiVjFjdDEwSlBfdWFB0gHbAUFVX3lxTE9rSjdBXzhKdHNhdXZjMHdaeHJfa3ZNUkZQaE95QmdPaWl3NEdKUkFrdjZtaG91d2h0ZmgwOEtlQnNLczJ5dUpZTnRXdWdrYTZBNnFJeUhwaWdsbUhBbmhyU2VyZ3FJa24welE0U25QMGg3TlJWVjZROG9UR1dXUVhRckN5MTJvX1dGdUJnbDREekRkdDB6anhPN0g3SEJMUFBVVzAtYjJaWGtEQktKOTJESWVrOUMzSElEVEZ3OWNHd3lGY2FPbmFnRzZ0Szg1VHRfZlF4YThfSW5zNA?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "НБУ почав не лише продавати, а й купувати валюту: що буде з курсом долара - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "13 липня 2026",
      "dateTS": 1783931237.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxQRUwxanl3U0xMN2p2ZVZJVlN4X3FkaTNRV2lrOVZWbVF1bDBkeDVXZVdpZHhKU3BlbHNxZHpJNVA2SEtiNXM3LUhTbkF2S1drYTN6YnVWeXdNOTJncTlpUTAxSjQyeHVfT2RYcS1sazNpRmdhQ2lubk9CQy1odFR5M3BsNnRKZ0t6TmhDZVoyYVMtTnBjZnVnbllxQTB1S3ExaHBoNFJYTTYzUkUxS19nMEtFSVA2ZmdMcXfSAbsBQVVfeXFMTy14Y09CVFZRQmtvdFZ1aWx4V3NlUTJnOVdpZFVTekZDTkxkWHdqTDVZQkVSOFd5WkpzZXRHcTB1aTlRVUJCOVZjWXlZYWJtU0R4SU53Ni1JZDFSY1hOclBTS0MxRHc0QnFiZGJMSlhUWTk1NUI2UThpRUVPQXJjZUMyNFA2MWl2ejl6NHlJX2Y0RklGUUkyaHVuQXM2SkgtR1lTY0g0cDNVb3dnRFBUZ0U5YmtIdmhrTHpicw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Це історичний рекорд: митниця показала, звідки Україна найбільше завозить техніку і транспорт - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "9 липня 2026",
      "dateTS": 1783580400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPX1BqS0NQNTVBUnRGaHV5VHhlZEg3UExrUUxpcVdyZi0td1ZNdTFBZTl5R3ZodjFDdW02YnZqZWNpbldzSXZjTFJDaHdaV0pFclhTV0hwS3hUNEpzU1l4Tm91QkxuYm9nT2ExVWhMQS1ZaDBKbUVJSW5VU3dqem1GbTF5U2s5V0tBbWdsckZkcVVQekQwZ01WYVh4Q05FR1pzLUF4TjduS2tYQ0lHWldxcG9ub9IBuAFBVV95cUxQZ0x1Ty1NZEw0U1RlcElzWEV6WGx2c1BCOHA1RmxIQjRjaWpncmlCMl9vczQ0bkNIcGxpRFAyakpJampvbDVZeThLNTJuZWcwXzdyVDZzXzhKRzRWSmc5NWZvNWlTNzN1b1ZxZXV6Njl3djl5VWl0NnRrRE50SUZHY3Rrc0JDZVd5YkNUTDNpdGc5VDdtRXpIM2gxRTFYY3BCR2g3NnhJVXRPX01wVTdtMmZaZlhvQzJk?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Курс валют на 9 липня: скільки коштують долар, євро та злотий - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "9 липня 2026",
      "dateTS": 1783569976.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxNck5FZkRTSm5RSEFIaTN1TW5ucGoxSTZRTGRfaDdkdy12dmljVV9PWmpQd05wSTJvQnlEOFlvSWM0TWUwTk5pRHdrWWl6eS1YcUZyNDJZSGdKM1RERThuTUR5bUdIX0Z4OXdGRll2U0dScWpwQnMydzRIWWZwWXhkQ1gtQlY1SHFJVDZEMlI0RUlaYmVFX0hYM2ZIT05DNHp1M3lxck5yd2FydEtWNl9YTGtmY2RRc3Y4OWVzZVhWYWpZbE9KNFpGdjNDMFZZMjdiSFHSAdMBQVVfeXFMUGdSbGUzYjQ2RjBQSF9aRndjTEFEbDJiT3ZBVEJSRUhxZGV0X2F4TF9ucnlwLVpRZWxjb2djYVdoQlpCT0JMMC1nMHNnaERsdEltR0VtMzNWSnZXZUZMODNSWl9CX0ZFZUJZc3lFaXdxV0ppbDg0UExIUmFJTUh2RVA5U0lUV0Q2emFNQWVVU2VYbnFTOVRIQU90ZzB1M0lSRHNFdWxBTmVlOXNjaF94Q2JrcGdGNTNpZ3MwaG9wYzBmUmJ6WWswcTh4RlZSXzhOUFc4UQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "UKR.NET",
      "title": "Попит на євро серед українців побив історичний рекорд - UKR.NET",
      "excerpt": "Згадка у виданні UKR.NET",
      "date": "7 липня 2026",
      "dateTS": 1783450266.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFB3S0o4UDdYUlNDSTUzVDR5NkIzbTV3T3RaY1ZkbE1QbkdiYzNJSFhLcHNwcG5hNnFmYW4zMG9tZnpZbGVoa21aSDE2R3c3a21GdWdXV1BNQnI1SW1VUV9rd2NlSlM3dUJl?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "my.ua",
      "title": "Кому підвищать зарплати і пенсії у липні: експерти ошелешили прогнозом - my.ua",
      "excerpt": "Згадка у виданні my.ua",
      "date": "30 червня 2026",
      "dateTS": 1782802800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxPekc0M2pINnlzeGxZbkYyMEx4MUdBYklVUWhJcndyTllOOUdrMGQwd0dmNnN6UGFiNU1FLXVIdjR3WHZ5eUN4RDlEeVNxazRBb2dZNm5rbkRKZ1lpckdkeWdGRDFxYWxvejQwWm4zMmdHcWlZTXAtU0Y4UXFnelZRcDVoNXNlM2V6M1hCOXQ4SGNRa0NDLVNiY2dyak5HZVBsaGNpX2hKUnJIaVh2NGZDa1NRZnMtZU9iQndxa3MxS18xdlU3ZnJ5MjNBUHBFVGtIZ2Uwa1RwMFFHZ1RkN0t3cjdmMUJtTHo50gHqAUFVX3lxTE5KMUtrcHNtTEJCdHlpNzcxUFZJUDlTVkNTUmdCVUhMeDlTbVdNN0dsczlSZjVuckQ3SFNNdUpuWks3eHRZMVhPOElhWnphMkl0RFVNQlpJd0NCNXp2M28tXzFIeFdVOHF3QUxoZkJlWkFSeHhRVnR6TkdUY1RIX1BHcGhqV3plQ3NqalNVcmZNSVRhYWZUdnNJeFZrMVBhLWFUelRyRS04SnNDSkk0SkdnLWhfZUxXNmRuaUM2eDEyTFRVcW1oY2VkMEpQWkdqczVITlZ3YTFoYlpreTFCWFI3QVVRSnpxcVJvZw?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "\"Утримувати 45 грн нескінченно неможливо\": яким буде курс долара у липні — прогноз експерта - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "28 червня 2026",
      "dateTS": 1782630000.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxNM0o5UlUtcEZPSkgtaWtrTFBoMUdRN09LR2FpMXJnSkRGTHVSb3lsTHNjZm1lQ3pEamRKUDF1Z2hNX1M5UmNJQkltMGZkZTNPMWJ3cVB3X0M2S1hPZUZmc3A5TXo2VHdWOFFLaXY2X0tEaE1LNWt3Q1BBMGw2TmQtSDNjdUhBeWxLS0k5WTR0TG1Ua1RNX3o3S1JTa1BQSmEyejBr0gGoAUFVX3lxTE41VlI5dTBLZjVSaGV1YmRvOW9LRndjZDJPMFJfM3RERmpmLThnRkxQaHhkblQyNk44MkVUaUZqRTN3U1FfWF9fMGw2Mmg2UWpXLVdMTVpkbThvbDRzY0h1TjBxSFVEczdkaEFjREZvN09xRklOR3R6NGRMUmxLU2Z4dE5iMmVvOUFOWUNsVHU0d2FraXJWQXAwTVJhdElhUkNxTnVqWWNKQQ?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Сценарій миру вже у НБУ: експерт звернув увагу на важливий сигнал після рішення про ставку 15% - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "19 червня 2026",
      "dateTS": 1781852400.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxNMHN6U3pScGVsQUwwanBkWWF0Y19keGstUlBybGRHa3diRGtBcjduS0YyQU9mSmlCUk4tckczb2RiVy16X0dJYlNHdzhFVjF4VnFtVkd5Wks0dGpxc1hSZFEyUDR3UmdyQWdVODBmczV4UTlYckFxdVlzelZ0ZDFQSW1VMjBaam9maS1YT0thcWJ3UkJycHBDMFlvR2xIQ01ZNlV2ZnNUdGY4aFRBZEVDSE5DRVYxVk1yclZTNG94bEPSAcYBQVVfeXFMTVhYdTV4OWlZVkd4LWt0UXY5RUpheDZkWHJUWU1hNHRDRWx6MHMyUTN3U25RcVlSZkUxcG1fWFBSYTJyM3JvLUxtbk0tUlRyeFlIZ2c4eTM1aUFOWE40a0xqOFRTNWMxMlpETHRKaWFIMWRtTk54WmJCN25DcWN5M0FXR0JZbGE5N3hpNXRUVXhJeDRyMjl0eXFrMWpjZVBTeDJpUUM3YU1BZGM0UFNwMWNyc3ZsNEV2aWRFME02aGtsUm5fQUhR?oc=5",
      "external": true,
      "featured": false
    },
    {
      "source": "news",
      "tag": "news",
      "tagLabel": "focus.ua",
      "title": "Долар шокував ринок, курс валют пробив психологічну межу — фінаналітик зробив прогноз на тиждень - focus.ua",
      "excerpt": "Згадка у виданні focus.ua",
      "date": "15 червня 2026",
      "dateTS": 1781506800.0,
      "readTime": "2 хв",
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOLUhBbjVXZm95VnVNM3JuYVhOcE42d0p2SkhwRG9FWk1VenhELTBka2ZzMjZEeTlWVkl0XzJEbmU1OFRUYWdOS2k4UGlxdERDUGo2anlqUl9sSlE2VzBfVV9OTmQxSkxoZjRFNklYNUxVMWlTMjByZnJVaTlIWWlOTmY3Y0duLTlPYzhBcVNZclRrRzBUdjBWMU90d3BZdEx5STlwRjZwTHFsdGd1eExPRVJtVUdfMUhE0gG-AUFVX3lxTFB5SkZBVkVpZTBJaTVaeGJneFdEYUp4NUpReXJERFpReU1mQXozZTZ6V0xVenBUT2dpcUduZHo4V04tR2djQVE4QXVjYkEyNHNEYzA3NkpvbWZHTzhNaW1ZMHNTT2FVczMtM1pyUnBoX2FkRFdkdGk5SWVVTG51Q3d1UUtUaWVURk9Vcms1aDRvSlVybWVSaVN3VUhZQUFNSjJPcF94ZUt0N001SmVIendLQ25JbEZsRkg1dFlWUmc?oc=5",
      "external": true,
      "featured": false
    }
  ],
  "youtube": [
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ПІДСУМКИ ЛИПНЯ - БОКОВИК ДОЛАРУ ЗА РАХУНОК ЗНАЧНИХ ІНТЕРВЕНЦІЙ. СЕРПЕНЬ РОЗСТАВИТЬ КРАПКИ НАД «І»",
      "excerpt": "00:00 вступ\n00:45 огляд липня 2026\n03:04 баланс ринку, попит та пропозиція\n07:35 головні події липня для ринку\n13:35 прогноз на серпень: фактори впливу\n18:00 базовий сценарій\n19:35 оптимістичний сцена",
      "date": "3 серпня 2026",
      "dateTS": 1785733234.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=aKwW09CAGas",
      "external": true,
      "featured": true
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ЗУПИНКА ПОРТІВ - ГОЛОВНИЙ НЕГАТИВ ДЛЯ ГРИВНІ. ВСІ СЛІДКУЮТЬ ЗА НБУ, ЯКИЙ ПОКИ ЩЕ ТРИМАЄ ДОЛАР",
      "excerpt": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ: 20–26 ЛИПНЯ 2026\n---\n00:00 Вступ\n00:41 Результати тижня 20-26 липня\n03:14 Баланс ринку: попит, пропозиція, дефіцит\n07:00 На що звурнув увагу на поточному тижні",
      "date": "25 липня 2026",
      "dateTS": 1784977422.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=tYvAcY3K6Mc",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ФЛЕШБЕКИ ДЛЯ ПОКУПЦІВ ВАЛЮТИ, АЛЕ НБУ ТРИМАЄ РАМКУ ДЛЯ ДОЛАРУ",
      "excerpt": "0:39 Огляд валютного ринку 13-19 липня\n3:15 Баланс ринку, попит та пропозиція, дефіцит, валютні інтервенції\n6:10 На що звернув увагу на тижні\n11:36 Прогноз динаміки курсу на 20-25 липня\n12:52 За чим с",
      "date": "18 липня 2026",
      "dateTS": 1784396204.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=V9y3jXRbAWc",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "НБУ ПОКАЗАВ ДІАПАЗОН КОЛИВАНЬ КУРСУ НА НАЙБЛИЖЧИЙ ЧАС",
      "excerpt": "ТИЖНЕВИЙ ОГЛЯД ВАЛЮТНОГО РИНКУ УКРАЇНИ\n\n00:38 Що відбулось на тижні 6-10 липня 2026\n02:37 Баланс ринку\n05:40 На що звернув увагу на тижні\n09:45 Очікування на 13-19 липня\n10:57 За чим слідкуємо на тижн",
      "date": "11 липня 2026",
      "dateTS": 1783800069.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=UADE6-VOSfg",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "НБУ ТРОМБУЄ ДОЛАР РЕКОРДНИМИ ІНТЕРВЕНЦІЯМИ. ПОЛІТИКА ЧИ ІНФЛЯЦІЯ? ПЕРЕХОДИМО В БОКОВИК",
      "excerpt": "00:00 вступ\n00:38 що відбувається на валютному ринку\n02:05 чому? політика чи інфляція?\n04:50 баланс ринку, попит та пропозиція, валютні інтервенції\n07:15 на що звернув увагу цього тижня\n10:55 очікуван",
      "date": "4 липня 2026",
      "dateTS": 1783195212.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=a1mVO9GBCd0",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ. ПОПЕРЕДНІ ПІДСУМКИ ЧЕРВНЯ 2026. ТРИ СЦЕНАРІЇ ДЛЯ КУРСУ НА ЛИПЕНЬ 2026.",
      "excerpt": "0:00 Результати червня 2026 загальні тренди\n5:01 Ринок в цифрах: попит, пропозиція, дефіцит, інтервенції НБУ\n9:14 Події червня, яки вплинули чи вплинуть на ринок\n14:06 Три сценарії на липень 2026\n19:5",
      "date": "27 червня 2026",
      "dateTS": 1782587703.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=QTtH3tdFvt0",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ДЕФІЦИТ УКРАЇНСЬКОГО ВАЛЮТНОГО РИНКУ СТРІМКО ЗРОСТАЄ, А НБУ ТРИМАЄ ДОЛАР Й ТИСНЕ НА ЄВРО",
      "excerpt": "00:34 - Що відбулось на ринку\n03:05 - Ринок в цифрах. Міжбанк \n05:11 - Ринок в цифрах. Готівковий ринок\n07:23 - На що звернув увагу на тижні\n12:12 - За чим спостерігаємо на новому тижні\n12:52 - Прогно",
      "date": "20 червня 2026",
      "dateTS": 1781982049.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=k7G6sdoXoNs",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ДОЛАР ПО 45, ЕКСПОРТЕРИ ПРИТРИМУЮТЬ ВАЛЮТУ, НБУ ЗАЛИВАЄ РИНОК ІНТЕРВЕНЦІЯМИ",
      "excerpt": "ВАЛЮТНИЙ РИНОК УКРАЇНИ ЗА ТИЖДЕНЬ: ЕКСПОРТЕРИ ПРИТРИМУЮТЬ ВАЛЮТУ, ДОЛАР 45 НОВИЙ РЕКОРД, НБУ ЗАПІЗНО ЗАЛИВАЄ РИНОК ІНТЕРВЕНЦІЯМИ\n---\nПочитати в FB https://www.facebook.com/AndyShev79 або в ТГ https://",
      "date": "13 червня 2026",
      "dateTS": 1781383209.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=qBrlyuvxcoU",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ ЗА ТИЖДЕНЬ: ДОЛАР НА РЕКОРДНОМУ РІВНІ Й ГОТОВИЙ РУШИТИ ДАЛІ",
      "excerpt": "Почитати на FB https://www.facebook.com/AndyShev79 та ТГ каналі https://t.me/shevchyshyn_trends \n\nЗа перший тиждень червня торгівельна активність українського валютного ринку, як й очікувалось, знизил",
      "date": "7 червня 2026",
      "dateTS": 1780826000.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=DUose7Z5PKk",
      "external": true,
      "featured": false
    },
    {
      "source": "youtube",
      "tag": "youtube",
      "tagLabel": "YouTube",
      "title": "ВАЛЮТНИЙ РИНОК УКРАЇНИ: ПІДСУМКИ ТРАВНЯ. ТРИ СЦЕНАРІЇ НА ЧЕРВЕНЬ.",
      "excerpt": "ТГ канал: https://t.me/shevchyshyn_trends \nFB: https://www.facebook.com/AndyShev79 \n---\nВАЛЮТНИЙ РИНОК ЗА ТРАВЕНЬ В ЦИФРАХ: \n• ДОЛАР: Долар на міжбанку зріс на 0,4% до 44,26 грн, встановивши новий іст",
      "date": "30 травня 2026",
      "dateTS": 1780155251.0,
      "readTime": "відео",
      "url": "https://www.youtube.com/watch?v=P_OpERiOWmY",
      "external": true,
      "featured": false
    }
  ]
};

// Поточний активний фільтр
let currentSource = "telegram";
const PAGE_SIZE = 8;
const shownCount = {};

function postCard(post, hasFeatured) {
  return `<a href="${post.url}" class="post-card${post.featured && hasFeatured ? " featured" : ""}"
     target="_blank" rel="noopener">
    <div class="post-tag">${post.tagLabel}</div>
    <div class="post-title">${post.title}</div>
    ${post.excerpt ? `<p class="post-excerpt">${post.excerpt}</p>` : ""}
    <div class="post-meta">${post.date} · ${post.readTime}</div>
  </a>`;
}

function renderPosts(source, reset) {
  currentSource = source;
  if (reset !== false) shownCount[source] = PAGE_SIZE;
  const posts = CONTENT[source] || [];
  const container = document.getElementById("posts-container");
  const moreBtn = document.getElementById("load-more-btn");
  if (!container) return;

  if (posts.length === 0) {
    container.innerHTML = `<p class="no-posts">${typeof t === "function" ? t("posts.empty") : "Публікацій поки немає"}</p>`;
    container.className = "posts-grid";
    if (moreBtn) moreBtn.style.display = "none";
    return;
  }

  const count = shownCount[source] || PAGE_SIZE;
  const visible = posts.slice(0, count);
  const hasFeatured = visible.some(p => p.featured);
  container.className = "posts-grid" + (hasFeatured ? " has-featured" : "");
  container.innerHTML = visible.map(p => postCard(p, hasFeatured)).join("");

  if (moreBtn) {
    const remaining = posts.length - count;
    if (remaining > 0) {
      moreBtn.style.display = "flex";
      const label = typeof t === "function" ? t("posts.more") : "Більше";
      moreBtn.textContent = `${label} (${remaining})`;
    } else {
      moreBtn.style.display = "none";
    }
  }
}

document.addEventListener("DOMContentLoaded", () => {
  renderPosts("telegram");

  document.querySelectorAll(".tab-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");
      renderPosts(btn.dataset.source);
    });
  });

  const moreBtn = document.getElementById("load-more-btn");
  if (moreBtn) {
    moreBtn.addEventListener("click", () => {
      shownCount[currentSource] = (shownCount[currentSource] || PAGE_SIZE) + PAGE_SIZE;
      renderPosts(currentSource, false);
    });
  }
});
